Handle refresh_whatsapp_tokens task exceptions
nyaruka/rapidpro pull request #2942
Opened 2020-08-28 12:34 UTC by koallann

If some request error occurs in a WhatsApp channel during the `refresh_whatsapp_tokens` task, the remaining channels are not refreshed, so future messages to be sent will fail due to an invalid token.

2020-09-14 18:04 UTC, norkans7 commented on temba/channels/types/whatsapp/tasks.py
> +                pass
@koallann just log this exception to sentry here

2020-09-14 18:04 UTC, norkans7 requested changes
Looks good just log the exception

2020-09-14 20:35 UTC, koallann commented on temba/channels/types/whatsapp/tasks.py
> +                pass
@norkans7 done

2020-09-14 20:40 UTC, norkans7 approved these changes

2020-09-16 15:31 UTC, norkans7 requested changes
@koallann please add a unit test to cover that missed lines

2020-10-16 10:43 UTC, norkans7 commented
Added by https://github.com/nyaruka/rapidpro/pull/3022

2020-10-16 10:43 UTC, closed without merging