Fix allow msg without topup
nyaruka/rapidpro pull request #2971
Opened 2020-09-08 20:47 UTC by norkans7

2020-09-08 20:56 UTC, nicpottier requested changes

2020-09-08 20:56 UTC, nicpottier commented on temba/msgs/migrations/0140_fail_msgs_missing_topups.py
> +    msgs = Msg.objects.filter(direction="O", topup=None, created_on__lte=day_ago)
Don't we want some status filters in here too? IE, `Q`?

2020-09-08 20:57 UTC, nicpottier commented on temba/msgs/migrations/0140_fail_msgs_missing_topups.py
> +    msgs = Msg.objects.filter(direction="O", topup=None, created_on__lte=day_ago)
Looking at TextIt, we also have a bunch of outgoing with a status of `E` without a topup, so should probably include those as well.

2020-09-08 21:26 UTC, norkans7 commented on temba/msgs/migrations/0140_fail_msgs_missing_topups.py
> +    msgs = Msg.objects.filter(direction="O", topup=None, created_on__lte=day_ago)
Filtered by `status__in=['Q', 'E']` so we do not change the delivered/sent/wired ones,

I limited to a day ago, I think newer messages being resent is fine.

2020-09-08 21:30 UTC, nicpottier approved these changes

2020-09-09 15:19 UTC, rowanseymour commented on temba/msgs/migrations/0140_fail_msgs_missing_topups.py
> +def fail_msg_without_topup(apps, schema_editor):  # pragma: no cover
no unit test... bold 😄

2020-09-09 15:23 UTC, merged