New WhatsApp BSP channel: 360dialog
nyaruka/rapidpro pull request #2980
Opened 2020-09-15 13:58 UTC by koallann

Submitting the PR https://github.com/rapidpro/rapidpro/pull/1280 in the correct repo this time.

2020-09-22 16:49 UTC, nicpottier approved these changes
Looks good.

2020-09-22 16:49 UTC, nicpottier commented
Can you merge master in again and we'll merge?

2020-09-22 16:57 UTC, koallann commented
done

2020-10-23 23:33 UTC, matmsa27 commented
Hi @nicpottier , do you have news about this PR? We running this in our environment for about 2 months and works fine.

2020-10-27 17:05 UTC, rowanseymour commented
@koallann sorry but can you merge in master again and I promise we'll try to merge this before we create more conflicts again!

2020-10-27 19:33 UTC, rowanseymour requested changes

2020-10-27 19:33 UTC, rowanseymour commented on templates/channels/types/dialog360/config.haml
> +  -blocktrans
should use `trimmed`

2020-10-27 19:33 UTC, rowanseymour commented on temba/channels/types/dialog360/views.py
> +            raise Exception(_("No org for this user, cannot claim"))
I guess you copied this from another channel type but it's not necessary and shouldn't be a localized string if it was any way. Can just remove.

2020-10-27 19:33 UTC, rowanseymour commented on temba/channels/types/dialog360/views.py
> +            "D3",
can use `self.channel_type`

2020-10-27 20:20 UTC, rowanseymour approved these changes

2020-10-27 20:21 UTC, rowanseymour commented
Nevermind above comments, I'll cleanup with all the other channel types in https://github.com/nyaruka/rapidpro/pull/3050

2020-10-27 20:21 UTC, merged