Allow channel role change
nyaruka/rapidpro pull request #3038
Opened 2020-10-21 20:06 UTC by norkans7

Fixes https://github.com/rapidpro/rapidpro/issues/577

2020-10-22 19:48 UTC, norkans7 commented
includes #3037

2020-10-23 16:56 UTC, rowanseymour commented
@norkans7 sorry think I caused some conflicts here.. also is supposed to be included again in https://github.com/nyaruka/rapidpro/pull/3037 ? That diff has the same changes

2020-10-23 17:18 UTC, rowanseymour commented
@norkans7 sorry to clarify, you're saying this PR includes https://github.com/nyaruka/rapidpro/pull/3037 but it looks like https://github.com/nyaruka/rapidpro/pull/3037 includes this PR no?

2020-10-23 17:21 UTC, norkans7 commented
#3037 needs to be merged first, I had worked from the same branch

The changes here are only in https://github.com/nyaruka/rapidpro/pull/3038/commits/783513fa6936d9b57b26f085ecf7af75e8b08a53

2020-10-23 17:36 UTC, rowanseymour commented
Ah ok - I saw the PR title of "Fix export styles" and the diff that is mostly changes to channel types and thought maybe it included something it shouldn't

2020-10-26 18:42 UTC, rowanseymour requested changes

2020-10-26 18:42 UTC, rowanseymour commented on temba/channels/types/external/views.py
> +        helps = {"address": _("Phone number of this device")}
address isn't a field... no?

2020-10-27 16:18 UTC, rowanseymour commented
@norkans7 seems this would require a change in goflow https://github.com/nyaruka/goflow/issues/974

2020-10-29 09:50 UTC, norkans7 commented
Added https://github.com/nyaruka/courier/pull/338 and https://github.com/nyaruka/goflow/pull/975

2020-10-29 20:01 UTC, merged