RocketChat channel
nyaruka/rapidpro pull request #3040
Opened 2020-10-22 14:15 UTC by koallann

Integration with the [RocketChat](https://rocket.chat) platform.

We've developed an [app](https://github.com/Ilhasoft/RCApps.RapidPro-Channel) that allows you to communicate with RocketChat users and visitors (from [omnichannel](https://docs.rocket.chat/guides/omnichannel-guides/omnichannel) module).

2020-10-22 14:16 UTC, koallann commented
RocketChat scheme on gocommon: https://github.com/nyaruka/gocommon/pull/37

2020-10-22 14:17 UTC, koallann commented
Handler on courier: https://github.com/nyaruka/courier/pull/336

2020-10-22 17:04 UTC, koallann commented
Note: the icon-rocketchat was added in the [RocketChat ticketer PR](https://github.com/nyaruka/rapidpro/pull/2909).

2020-10-28 15:06 UTC, rowanseymour requested changes

2020-10-28 15:06 UTC, rowanseymour commented on temba/channels/types/rocketchat/type.py
> +    )
Just merged https://github.com/nyaruka/rapidpro/pull/3050 which tries to introduce a better convention for these strings to make them easier to localize, so this would be:

```python
claim_blurb = _("Add a %(link)s bot to send and receive messages to Rocket.Chat users.") % {
    "link": '<a href="http://africastalking.com">Rocket.Chat</a>'
}
```

2020-10-28 15:06 UTC, rowanseymour commented on templates/channels/types/rocketchat/claim.haml
> +        On your RocketChat, go to <i>Administration > Omnichannel</i> and enable it.
shouldn't `>` be escaped as `&gt;`?

2020-10-28 15:06 UTC, rowanseymour commented on templates/channels/types/rocketchat/claim.haml
> +    margin-top: 0.3em;
indentation

2020-10-28 15:06 UTC, rowanseymour commented on temba/contacts/tests.py
> +        with self.assertNumQueries(50):
assuming this a weird merge issue... not seeing anything that adds db hits

2020-10-29 16:26 UTC, rowanseymour commented on templates/channels/types/rocketchat/claim.haml
> +    - blocktrans
`-blocktrans trimmed`

2020-10-30 00:49 UTC, jcbalmeida commented on temba/contacts/tests.py
> +        with self.assertNumQueries(50):
It actually adds: https://github.com/nyaruka/rapidpro/blob/f5af773c5b3b410e5d22206a959c51adb51d3f48/temba/contacts/models.py#L1878
A sincere question: Should we really test the number of queries to the database, since not only can the number of schemas but anything else related to the data model change that number?

2020-11-02 20:49 UTC, merged