Globals UI should limit creation of globals to org limit
nyaruka/rapidpro pull request #3054
Opened 2020-10-29 13:18 UTC by norkans7

Fixes https://github.com/rapidpro/rapidpro/issues/1360

2020-10-29 14:57 UTC, rowanseymour requested changes

2020-10-29 14:57 UTC, rowanseymour commented on temba/globals/tests.py
> -    @override_settings(MAX_ACTIVE_GLOBALS_PER_ORG=4)
Oh weird.. so we have both this setting and the constant in `Global`.. and they're different numbers.. my bad 🤦 

And I see we have `ContactGroup.MAX_ORG_CONTACTGROUPS` but `settings.MAX_ACTIVE_CONTACTFIELDS_PER_ORG`

I think eventually these become settings on org (@nicpottier ?).. but in the name of consistency let's go with these settings:

```
MAX_ACTIVE_CONTACTFIELDS_PER_ORG = 250
MAX_ACTIVE_CONTACTGROUPS_PER_ORG = 250
MAX_ACTIVE_GLOBALS_PER_ORG = 250
```

For bonus points you could make it a method of org like..

```
org.get_limit(Org.LIMIT_FIELDS)
org.get_limit(Org.LIMIT_GLOBALS)
org.get_limit(Org.LIMIT_GROUPS)
```

That for now just returns those settings values but in future reads from something on the org model.

2020-10-30 16:14 UTC, norkans7 commented on temba/globals/tests.py
> -    @override_settings(MAX_ACTIVE_GLOBALS_PER_ORG=4)
Updated the PR

2020-10-30 16:59 UTC, norkans7 commented on temba/settings_common.py
> -# Maximum active objects are org can have
We lost the ability to customize these, I am not sure if anyone was using that

2020-10-30 19:00 UTC, rowanseymour approved these changes
👍

2020-10-30 19:01 UTC, merged