Refresh template messages for 360dialog Channels
nyaruka/rapidpro pull request #3083
Opened 2020-11-18 12:49 UTC by jcbalmeida

* Creates a scheduled task to refresh the message tempaltes through 360dialog API (https://docs.360dialog.com/api/whatsapp-api/message-templates-api)
* The task is registered within settings.CELERYBEAT_SCHEDULE (15 min. interval, like wpp refresh task)
* Adds the relative haml templates (templates.haml and sync_logs.haml)

There is some differences between the official WhatsApp API and 360dialog, an important one is the templates list response does not provide the templates ids. I managed it using the key "language/name" as external_id.

2020-11-18 14:06 UTC, rowanseymour requested changes
Probably can't merge this this week as we're still in code-freeze for 6.0. 

Does seem to be some duplication with this and the existing whatsapp channel around template management.. wondering how we can reduce that..

2020-11-18 14:06 UTC, rowanseymour commented on temba/channels/types/dialog360/type.py
> +LANGUAGE_MAPPING = dict(
This seems to be a duplication of what's in `whatsapp/type.py`. It also seems we could figure this stuff out programatically no? There are other places where we lean on pycountry to map between language codes.

2020-11-18 14:06 UTC, rowanseymour commented on templates/channels/types/dialog360/sync_logs.haml
> +          %th{ style:'width:150px' }
use new HAML syntax - `%th(style="width:150px")`. I know there's there's lots of code using the older syntax but we're trying to use the new syntax for new code

2020-11-18 14:06 UTC, rowanseymour commented on templates/channels/types/dialog360/sync_logs.haml
> +  -trans "360dialog Templates Events"
`360dialog Template Events` maybe?

2020-12-15 17:01 UTC, matmsa27 commented
Hi @rowanseymour , can we move with this evolution on WhatsApp 360 Channel? This feature is very special because can improve the use of this channel by automatically way to getting template message from 360 base, and use on Rapidpro and then sending to the contacts.

2020-12-15 17:13 UTC, rowanseymour commented on temba/channels/types/dialog360/tasks.py
> +def _calculate_variable_count(content):
Still have quite a bit of functionality like this duplicated between `types/dialog360` and `types/whatsapp`, and perhaps soon `types/twilio_whatsapp` and `types/textit_whatsapp`. Maybe this stuff could move to `temba.utils.whatsapp`? @nicpottier @norkans7 ?

2020-12-15 17:18 UTC, rowanseymour commented on templates/channels/types/dialog360/sync_logs.haml
> +-extends "channels/channel_read.html"
This is also duplicates `templates/channels/types/whatsapp/sign_logs.haml`. Seems like we could have a shared Sync Logs view. Maybe not something we need to address now tho.

2020-12-15 18:08 UTC, nicpottier requested changes
Agree with Rowan that some effort should be taken to share functionality with the main WhatsApp channel as most of this functionality is identical. Can you refactor to make sure that's the case?

2020-12-17 14:20 UTC, matmsa27 commented
I agree with you guys, we can refactor this. I believe the task for refreshing templates can be on `temba.utils.whatsapp` and all channels (WhatsApp, 360, Kaleyra, TextIt and Twilio) for WhatsApp can use the same task, only changing some parameters like URL, headers, and other points that we can discuss, what do you think?

2020-12-17 14:59 UTC, rowanseymour commented
I think my preference would be actually be `temba.channels.whatsapp` if this is going to include tasks and UI stuff

2021-05-12 17:45 UTC, rowanseymour commented
Closed in favor of https://github.com/nyaruka/rapidpro/pull/3301

2021-05-12 17:45 UTC, closed without merging