Flow start filters Part 2
nyaruka/rapidpro pull request #3150
Opened 2021-01-19 17:43 UTC by norkans7

2021-02-02 19:57 UTC, rowanseymour requested changes

2021-02-02 19:57 UTC, rowanseymour commented on temba/flows/models.py
> +        (TYPE_MANUAL, _("Manual")),
I don't think we're going to use these in the UI so they don't need to be localized

2021-02-02 20:04 UTC, rowanseymour requested changes

2021-02-02 20:04 UTC, rowanseymour commented on temba/flows/migrations/0248_install_triggers_flows_start_type_count.py
> +def populate_flow_start_filter_counts(apps, schema_editor):  # pragma: no cover
we write unit tests for data migrations these days 😄

2021-02-02 20:04 UTC, rowanseymour commented on temba/flows/migrations/0248_install_triggers_flows_start_type_count.py
> +# Generated by Django 2.2.10 on 2021-01-20 18:59
I think we need to ship this migration separately so it can be faked and the run offline later. It also needs to clear out existing counts added by the trigger. All things to put in the unit test!

2021-02-03 13:18 UTC, norkans7 commented
We stopped using this approach and we will display the flow start trigger type in contact history 
https://github.com/nyaruka/rapidpro/pull/3153

2021-02-03 13:18 UTC, closed without merging

2021-02-03 14:11 UTC, rowanseymour commented
Huh I thought we were going to do a bit of both.. but if we're ditching this then we should cleanup https://github.com/nyaruka/rapidpro/pull/3149

2021-02-03 14:37 UTC, norkans7 commented
No we keep that index as we'll show the type toggle on top of the list but this PR was about adding counts for the left menu and we no longer need that.

2021-02-03 14:41 UTC, rowanseymour commented
But don't we need counts to do any sort of paging?