Display flow start trigger description in contact history
nyaruka/rapidpro pull request #3153
Opened 2021-01-22 14:35 UTC by norkans7

2021-01-22 14:38 UTC, norkans7 commented
<img width="1007" alt="0788 123 123 2021-01-22 16-29-55" src="https://user-images.githubusercontent.com/1040571/105503988-ebdc4880-5ccf-11eb-8ff7-52d40ae467df.png">
<img width="1045" alt="0788 123 123 2021-01-22 16-29-22" src="https://user-images.githubusercontent.com/1040571/105504000-eed73900-5ccf-11eb-9398-7aec67df3827.png">
<img width="1111" alt="0788 123 123 2021-01-22 16-28-50" src="https://user-images.githubusercontent.com/1040571/105504003-ef6fcf80-5ccf-11eb-9ad5-b11bc3e7a7dd.png">
<img width="1032" alt="0788 123 123 2021-01-22 16-28-12" src="https://user-images.githubusercontent.com/1040571/105504007-f0086600-5ccf-11eb-8b03-37af39e57d06.png">
<img width="997" alt="0788 123 123 2021-01-22 16-27-23" src="https://user-images.githubusercontent.com/1040571/105504010-f0a0fc80-5ccf-11eb-9cd7-de56a5a36bc9.png">

2021-01-22 15:11 UTC, rowanseymour commented
I think the approach of describing things in sentences works best when the nouns of interest are clickable links. So for example for the campaign event case:

<img width="490" alt="Captura de Pantalla 2021-01-22 a la(s) 10 08 09" src="https://user-images.githubusercontent.com/675558/105507904-bfa5d500-5c99-11eb-8897-95f98cbedaeb.png">

Unfortunately that's not really possible for things like users and triggers since they don't have read pages...

2021-01-22 15:13 UTC, rowanseymour commented on temba/flows/models.py
> +        try:
why is this a `try/except` and not a `if/elif/elif..` ?

2021-01-22 16:24 UTC, rowanseymour commented on temba/flows/models.py
> +        try:
Also this is kinda going the opposite direction of where I'm trying to contact history events right now - these are strings rather than structured data, so if for example you wanted to link to a campaign event, you'd end up putting HTML here.

So maybe let's hold off for a tiny bit here so we can get all these events into JSON

2021-01-22 16:29 UTC, norkans7 commented on temba/flows/models.py
> +        try:
Okay, I'll wait

2021-02-17 16:17 UTC, rowanseymour requested changes

2021-02-17 16:17 UTC, rowanseymour commented on temba/mailroom/events.py
> +        trigger_description = session.show_trigger_description() if session else None
I think there's two issues with this approach:

1. All runs in the session are treated as being triggered by the session trigger - it should only be the first run in each session
2. We're parsing the session JSON twice - we're already parsing it to extract session events so it seems like it would more efficient to grab trigger information then

I was thinking maybe we create `flow_entered` events in `get_session_events`, decorate them with trigger information, and then merge those with the `flow_entered` events created from `FlowRun` instances.

2021-02-26 15:02 UTC, rowanseymour requested changes

2021-02-26 15:02 UTC, rowanseymour commented on temba/contacts/models.py
> +                        FlowEntered(
Feels like this could be simpler. Instead of having this helper class and creating a JSON like thing here which is later converted to the event.. just create the event. Pass `run` and `session.output["trigger"]` to a method on `Event` and return an event dict. No deepcopy required.

2021-02-26 15:02 UTC, rowanseymour commented on temba/contacts/models.py
> +        started_runs = [r for r in runs if not r.session and after <= r.created_on < before]
Isn't this going to be an extra db hit or has Django gotten smarter? (if not use `r.session_id`)

2021-02-26 20:02 UTC, norkans7 commented on temba/contacts/models.py
> +                        FlowEntered(
we do not have a user here so we cannot decide on the session URL, I think the helper class will use a renderer to decide on that. Do we ignore the session URL for this event?

2023-01-17 02:00 UTC, closed without merging