Logout user to force login to accept invite and require invite email …
nyaruka/rapidpro pull request #3180
Opened 2021-02-08 10:44 UTC by norkans7

…account exactly

2021-02-08 10:47 UTC, norkans7 commented
<img width="861" alt="RapidPro - Visually build nationally scalable mobile applications 2021-02-08 11-51-53" src="https://user-images.githubusercontent.com/1040571/107209663-c52a4b80-6a0b-11eb-881a-46dc9e75f39a.png">
<img width="935" alt="RapidPro - Visually build nationally scalable mobile applications 2021-02-08 11-51-38" src="https://user-images.githubusercontent.com/1040571/107209669-c8bdd280-6a0b-11eb-9f5d-470661cdd4d6.png">

2021-02-08 17:39 UTC, rowanseymour requested changes

2021-02-08 17:39 UTC, rowanseymour commented on temba/orgs/tests.py
> +        def create_user(username):
I think put this on `TembaTest`.. there's a similar function in `SmartminTest` but it creates emails like `Adminstrator@nyaruka.com`

2021-02-08 17:39 UTC, rowanseymour commented on temba/orgs/views.py
> +                if not has_user:
Seems like if the currently logged in user is this user... we could redirect straight to the accept page? @nicpottier?

2021-02-08 17:39 UTC, rowanseymour commented on temba/orgs/views.py
> +            invitations = Invitation.objects.filter(secret=secret, is_active=True)
`.first()`

2021-02-08 17:54 UTC, nicpottier commented on temba/orgs/views.py
> +                if not has_user:
Sure seems that way.

2021-02-08 18:05 UTC, nicpottier commented
Maybe it's worth adding a disabled state to temba-components inputs? Seems like both the login and create login forms could benefit from that.

2021-02-18 14:29 UTC, norkans7 commented
<img width="1105" alt="RapidPro - Visually build nationally scalable mobile applications 2021-02-18 16-28-29" src="https://user-images.githubusercontent.com/1040571/108371481-76986080-7206-11eb-83d0-b50123399f3e.png">
<img width="1125" alt="RapidPro - Visually build nationally scalable mobile applications 2021-02-18 16-28-19" src="https://user-images.githubusercontent.com/1040571/108371494-7ac47e00-7206-11eb-856c-c114fd459636.png">

2021-02-18 16:41 UTC, rowanseymour requested changes

2021-02-18 16:41 UTC, rowanseymour commented on temba/orgs/views.py
> +        def pre_process(self, request, *args, **kwargs):  # pragma: needs cover
`# pragma: needs cover` looks like this bit needs coverage? Actually I think it might already be covered by your tests...

2021-02-18 16:41 UTC, rowanseymour commented on templates/orgs/org_join.haml
> +          %form#login-form{method:"post", action:"{% url 'users.user_login' %}?next={% url 'orgs.org_join_accept' secret %}"}
`(method="post"...`

2021-02-18 16:41 UTC, rowanseymour commented on templates/orgs/org_join_accept.haml
> +      -trans "Please click Join to accept the invitation."
Am still wondering if this extra step is really necessary... especially in the case of the user creating a new login, it seems a little redundant to then ask them if they actually want to join the workspace... if they don't click the button they're left with the login with no workspaces... it's not a big deal either way.

2021-02-19 19:04 UTC, rowanseymour approved these changes

2021-02-22 14:18 UTC, merged