Support customization for org limits
nyaruka/rapidpro pull request #3222
Opened 2021-03-10 20:45 UTC by norkans7

2021-03-10 21:12 UTC, norkans7 commented
Addresses https://github.com/rapidpro/rapidpro/issues/1458

2021-03-10 21:15 UTC, norkans7 commented
<img width="835" alt="RapidPro - Visually build nationally scalable mobile applications 2021-03-10 23-13-56" src="https://user-images.githubusercontent.com/1040571/110698519-6caac180-81f6-11eb-92f4-17de743f7b00.png">

When some limits not set(using the settings defaults)
<img width="841" alt="RapidPro - Visually build nationally scalable mobile applications 2021-03-10 23-14-30" src="https://user-images.githubusercontent.com/1040571/110698504-69173a80-81f6-11eb-9fdc-a5c79b187738.png">

2021-03-15 20:53 UTC, rowanseymour requested changes

2021-03-15 20:53 UTC, rowanseymour commented on temba/orgs/models.py
> -        raise ValueError("Invalid org limit type")
I think a cleaner way to organize this method would be to create a dict class variable like 

```
LIMIT_DEFAULTS = {
  LIMIT_FIELDS: settings.MAX_ACTIVE_CONTACTFIELDS_PER_ORG,
  ...
}
```

and then the lookup becomes `self.limits.get(limit_type, self.LIMIT_DEFAULTS.get(limit_type))`

2021-03-15 20:53 UTC, rowanseymour commented on temba/orgs/models.py
> +        if limit_type not in [Org.LIMIT_FIELDS, Org.LIMIT_GROUPS, Org.LIMIT_GLOBALS]:
not sure this is really necessary since it's we who always call this method.. but it could be an assert like 

`assert limit_type in (Org.LIMIT_FIELDS, Org.LIMIT_GROUPS, Org.LIMIT_GLOBALS)`

2021-03-16 13:02 UTC, norkans7 commented on temba/orgs/models.py
> -        raise ValueError("Invalid org limit type")
That is now updated

2021-03-16 14:38 UTC, nicpottier commented on temba/orgs/models.py
> +            return int(self.LIMIT_DEFAULTS.get(limit_type))
I think the `get` backdown Rowan suggested is a bit cleaner. Generally you want to keep Exceptions to the exceptional/error cases.

2021-03-16 14:42 UTC, rowanseymour commented on temba/orgs/models.py
> +            return int(self.LIMIT_DEFAULTS.get(limit_type))
This is fine but it's more complicated than it needs to be. It's we who write the limits field, so we can make sure we don't put non-numbers in there. If somehow we do by accident, then it's fine to blow up with a `ValueError` because we'll see that in sentry and go fix the problem - with this `try/except` the problem remains hidden because the exception is handled.

The assert above also makes me think we should be using an enum so it's checked at a type level - now if you add new limit types you need to remember to include them in this check...

2021-03-16 14:48 UTC, norkans7 commented on temba/orgs/models.py
> +            return int(self.LIMIT_DEFAULTS.get(limit_type))
Okay, I can change both of those to be simply lookup the value

2021-03-16 15:48 UTC, rowanseymour approved these changes

2021-03-16 15:48 UTC, merged