Add support for YYYY-MM-DD date format
nyaruka/rapidpro pull request #3243
Opened 2021-03-25 11:05 UTC by norkans7

2021-03-25 13:20 UTC, rowanseymour commented on temba/orgs/models.py
> +            return "day_first"
can we maybe get rid of this? we already have 2 representations of the different date values (D, M , Y) vs (DD-MM-YYYY etc)

2021-03-25 13:21 UTC, rowanseymour commented on temba/orgs/models.py
>      def get_datetime_formats(self):
use a class dict for this like `DATE_FORMATS_PYTHON = {DATE_FORMAT_DAY_FIRST: "%d-%m-%Y", ...}`

2021-03-25 13:22 UTC, rowanseymour requested changes
see comments

2021-03-25 13:24 UTC, norkans7 commented on temba/orgs/models.py
> +            return "day_first"
This is used on the public API
https://github.com/nyaruka/rapidpro/blob/9efc910a4a5912ae2fe4b431c5687ff5d2d9fced/temba/api/v2/views.py#L3510

We might break someone's code I guess

2021-03-25 13:28 UTC, rowanseymour commented on temba/orgs/models.py
> +            return "day_first"
Ah ok then make this a dict and put it in the API package with the serializer function

2021-03-25 13:29 UTC, norkans7 commented on temba/orgs/models.py
> +            return "day_first"
Ok

2021-03-25 14:12 UTC, rowanseymour requested changes

2021-03-25 14:12 UTC, rowanseymour commented on temba/orgs/models.py
> +    DATE_FORMATS = {
I think you want two dicts.. `DATE_FORMATS_ENGINE` and `DATE_FORMATS_PYTHON`

`get_datetime_formats` is currently reading from this one which seems wrong

2021-03-25 14:22 UTC, norkans7 commented on temba/orgs/models.py
> +    DATE_FORMATS = {
Ohh right

2021-03-25 16:13 UTC, rowanseymour commented on temba/orgs/models.py
> +        return str_to_datetime(s, self.timezone, self.date_format == Org.DATE_FORMAT_DAY_FIRST)
not that we use this very much.. but this isn't going to work for YMD dates right?

2021-03-25 17:58 UTC, norkans7 commented on temba/orgs/models.py
> +        return str_to_datetime(s, self.timezone, self.date_format == Org.DATE_FORMAT_DAY_FIRST)
I do not think we we can have a date with year first and not 4 digits for the year.
So that would work 

https://github.com/nyaruka/rapidpro/blob/9efc910a4a5912ae2fe4b431c5687ff5d2d9fced/temba/utils/tests.py#L301

2021-03-25 18:18 UTC, rowanseymour commented on temba/orgs/models.py
> +        return str_to_datetime(s, self.timezone, self.date_format == Org.DATE_FORMAT_DAY_FIRST)
So I'd forgotten that all contact field updates are now done in mailroom... I don't think we actually used this method anymore. If not, you can have the pleasure of ripping it out.

2021-03-25 18:20 UTC, norkans7 commented on temba/orgs/models.py
> +        return str_to_datetime(s, self.timezone, self.date_format == Org.DATE_FORMAT_DAY_FIRST)
Okay, I will check more on that

2021-03-26 12:41 UTC, norkans7 commented on temba/orgs/models.py
> +        return str_to_datetime(s, self.timezone, self.date_format == Org.DATE_FORMAT_DAY_FIRST)
I think our tests still rely on that

https://github.com/nyaruka/rapidpro/blob/ecddb4a7421ba5b3693fba750241005370b84420/temba/tests/mailroom.py#L354


https://github.com/nyaruka/rapidpro/blob/ecddb4a7421ba5b3693fba750241005370b84420/temba/tests/mailroom.py#L414

2021-03-26 12:44 UTC, norkans7 commented on temba/orgs/models.py
> +        return str_to_datetime(s, self.timezone, self.date_format == Org.DATE_FORMAT_DAY_FIRST)
Probably the cleanup can be to move all those methods in the tests files

2021-03-26 13:19 UTC, rowanseymour commented on temba/orgs/models.py
> +        return str_to_datetime(s, self.timezone, self.date_format == Org.DATE_FORMAT_DAY_FIRST)
Exactly - just put a date parsing function in tests/mailroom.py that's "close enough" to what mailroom does

2021-03-26 13:56 UTC, norkans7 commented on temba/orgs/models.py
> +        return str_to_datetime(s, self.timezone, self.date_format == Org.DATE_FORMAT_DAY_FIRST)
Ok

2021-03-29 17:09 UTC, rowanseymour commented on temba/orgs/models.py
> +    DATE_FORMATS_CHOICES = (
would just tweak this to `DATE_FORMAT_CHOICES`.. the double plural is a little odd

2021-03-29 17:09 UTC, rowanseymour approved these changes

2021-03-29 20:38 UTC, rowanseymour approved these changes

2021-03-29 20:38 UTC, merged