Refactor WhatsApp templates
nyaruka/rapidpro pull request #3288
Opened 2021-05-04 15:24 UTC by norkans7

2021-05-04 15:58 UTC, norkans7 commented
No logic change yet, just move the code to a reusable `temba.utils.whatsapp` package

2021-05-04 21:49 UTC, rowanseymour requested changes

2021-05-04 21:49 UTC, rowanseymour commented on templates/utils/whatsapp/templates.haml
> +    -trans "Whatsapp Templates are synced from your account every 15 minutes."
WhatsApp

2021-05-05 13:55 UTC, rowanseymour approved these changes

2021-05-05 13:55 UTC, merged