Assignment
nyaruka/rapidpro pull request #3387
Opened 2021-06-25 01:42 UTC by ericnewcomer

* Add assign view
* Add filters for unassigned and my tickets
* Add assignee to ticketing endpoints
* Assignment features in components

2021-06-25 18:46 UTC, rowanseymour commented on temba/api/v2/serializers.py
> +            {"id": obj.assignee.id, "first_name": obj.assignee.first_name, "last_name": obj.assignee.last_name}
So in the engine I figured it was a nice simplicity to just combine first/last name into a single `name` - every other asset type is identifier+name, and contacts also have a single name. Django's first/last name thing is also arguably a little western centric..

So we have...

```
@ticket.assignee       -> Jim McTickets
@ticket.assignee.email -> jim@tickets.com
@ticket.assignee.name  -> Jim McTickets
```

and a user reference is `{"email": "jim@tickets.com", "name": "Jim McTickets"}`

That doesn't mean that API has to match that - we already have to massage some API representations into flow spec representations, but things like events which come from the engine won't have first/last name when they reference a user...

2021-06-25 18:46 UTC, rowanseymour commented on temba/tickets/views.py
> +        super().__init__(**kwargs)
is this needed?

2021-06-25 18:48 UTC, rowanseymour commented on temba/api/v2/serializers.py
> +            {"id": obj.assignee.id, "first_name": obj.assignee.first_name, "last_name": obj.assignee.last_name}
And also now looking at this I'm thinking I need to go back and tweak it so that `@ticket.assignee.__default__` fallback on email if there is no name...

2021-06-29 21:21 UTC, ericnewcomer commented on temba/api/v2/serializers.py
> +            {"id": obj.assignee.id, "first_name": obj.assignee.first_name, "last_name": obj.assignee.last_name}
Totally down with representing users universally in this way after this is merged

2021-06-29 22:28 UTC, rowanseymour commented on temba/api/v2/serializers.py
> +            {"id": obj.assignee.id, "first_name": obj.assignee.first_name, "last_name": obj.assignee.last_name}
Yeah I don't think this is much of an issue - just that if/when the editor starts putting users in flows it will be as email+name references - or if the simulator needs to consume events from the engine with user references they will be email+name as well.

2021-06-30 18:45 UTC, rowanseymour commented on temba/tests/crudl.py
> +            if value is not None:
maybe better to change below to `form.initial.get(field_key)` so that we're still testing empty initial values

2021-06-30 19:48 UTC, ericnewcomer commented on temba/tests/crudl.py
> +            if value is not None:
Sure.

2021-06-30 23:21 UTC, rowanseymour requested changes

2021-06-30 23:21 UTC, rowanseymour commented on temba/tickets/types/mailgun/views.py
> +            name=to_address,
what was the reason for this? The current ticketer names are like...

```
Email (<emailaddress>)
Zendesk (<subdomain>)
RocketChat (<host>)
```

2021-06-30 23:23 UTC, rowanseymour requested changes

2021-06-30 23:23 UTC, rowanseymour commented on templates/tickets/ticket_list.haml
> +          %temba-option(name="My Tickets" value="M" icon="coffee")
trans

2021-07-01 00:10 UTC, ericnewcomer commented on temba/tickets/types/mailgun/views.py
> +            name=to_address,
I feel an email address is sufficiently identifiable as email.

2021-07-01 00:19 UTC, ericnewcomer commented on temba/tickets/types/mailgun/views.py
> +            name=to_address,
...but also that the type should not be encoded in the name. That should be left up to the UI.

2021-07-01 00:45 UTC, rowanseymour commented on temba/tickets/types/mailgun/views.py
> +            name=to_address,
But is it sufficiently identifiable as an email-based ticketer? It just seems odd that the other types now have type in the name but email is just a bare email address... if we have a page where we render a ticketer name as a link.. it's going to look like a mailto link.

2021-07-01 00:48 UTC, ericnewcomer commented
Agreed. Let’s take the ticketer type out of those too and let the ui decide
how to display the type.


On Wed, Jun 30, 2021 at 5:45 PM Rowan Seymour ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In temba/tickets/types/mailgun/views.py
> <https://github.com/nyaruka/rapidpro/pull/3387#discussion_r661897624>:
>
> > @@ -97,7 +97,7 @@ def form_valid(self, form):
>              user=self.request.user,
>              ticketer_type=MailgunType.slug,
>              config=config,
> -            name=f"Email ({to_address})",
> +            name=to_address,
>
> But is it sufficiently identifiable as an email-based ticketer? It just
> seems odd that the other types now have type in the name but email is just
> a bare email address... if we have a page where we render a ticketer name
> as a link.. it's going to look like a mailto link.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/nyaruka/rapidpro/pull/3387#discussion_r661897624>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABTVRAUTPTMWZ2PYZVOYP3TVO3C7ANCNFSM47I6SE3Q>
> .
>

2021-07-01 00:52 UTC, rowanseymour commented on temba/tickets/types/mailgun/views.py
> +            name=to_address,
Well anyways not worth holding this up, can tweak in future if it gets weird

2021-07-01 15:09 UTC, merged