📝 Tweak trigger forms for clarity
nyaruka/rapidpro pull request #3411
Opened 2021-07-07 22:26 UTC by rowanseymour

<img width="700" alt="Captura de Pantalla 2021-07-07 a la(s) 17 16 28" src="https://user-images.githubusercontent.com/675558/124836223-3aad3000-df48-11eb-9d06-e31be8869856.png">
<img width="700" alt="Captura de Pantalla 2021-07-07 a la(s) 17 15 43" src="https://user-images.githubusercontent.com/675558/124836220-397c0300-df48-11eb-9656-c57badc1096e.png">

2021-07-07 22:29 UTC, nicpottier requested changes

2021-07-07 22:29 UTC, nicpottier commented on temba/triggers/views.py
> +        help_text=_("The groups that will be started in the flow."),
So to me this reads right for scheduled trigger case but not for the keyword case. I think that's the rub, we want these to be different. (previous text was fine and clear for the keyword case)

2021-07-08 14:39 UTC, rowanseymour commented
@nicpottier updated

<img width="699" alt="Captura de Pantalla 2021-07-08 a la(s) 09 38 17" src="https://user-images.githubusercontent.com/675558/124941260-4d6b4780-dfd0-11eb-9721-f4d2c69b9c98.png">
<img width="701" alt="Captura de Pantalla 2021-07-08 a la(s) 09 38 28" src="https://user-images.githubusercontent.com/675558/124941251-4c3a1a80-dfd0-11eb-8647-47454ecb677e.png">

2021-07-08 16:07 UTC, nicpottier approved these changes
woot

2021-07-08 16:20 UTC, merged