Cookie based opt in and out of new interface
nyaruka/rapidpro pull request #3616
Opened 2021-12-04 07:16 UTC by ericnewcomer

Merge #3615 first as this includes it

2021-12-14 14:17 UTC, rowanseymour commented on temba/msgs/tests.py
> +        with self.assertNumQueries(37):
not seeing where these are coming from..?

2021-12-14 14:27 UTC, rowanseymour requested changes

2021-12-14 14:27 UTC, rowanseymour commented on templates/orgs/user_account.haml
> +      for now.
maybe don't worry about localization since it's a temporary thing.. but you can't localize things like "old one" and string them together and expect to get a meaningful sentence

2021-12-14 14:27 UTC, rowanseymour commented on temba/msgs/tests.py
> +        with self.assertNumQueries(37):
not seeing where these are coming from.. it's only 2 queries but it'd be nice to know

2022-02-01 23:00 UTC, ericnewcomer commented on temba/msgs/tests.py
> +        with self.assertNumQueries(37):
This is from checking beta status of the user in the template

2022-02-02 16:13 UTC, rowanseymour approved these changes

2022-02-02 16:26 UTC, merged