Contact imports should strip empty rows, missing a UUID or URNs
nyaruka/rapidpro pull request #3666
Opened 2022-01-27 09:04 UTC by norkans7

2022-01-27 16:57 UTC, rowanseymour commented
I think we should..

1. Update `ContactImport.try_to_parse` to track `num_ignored` alongside `num_records`.. that way we can then show users how many rows we will actually import from their file. That way if someone tries to import a file of just names, we'll raise a validation error.
2. [ideally, not crucial] Update the batch building so we still create batches of equal sizes even if we're skipping over rows

2022-01-27 23:01 UTC, norkans7 commented
I addressed that, I thought it is not needed to record `num_ignored` on the DB row.
I am happy to add that if we need to display that on the preview view.
Current way we show validation error when the file has no valid record, I think that is enough

2022-02-01 19:19 UTC, rowanseymour requested changes

2022-02-01 19:19 UTC, rowanseymour commented on temba/contacts/models.py
> +        valid_records_count = 0
I think simpler to use `num_records` as valid records.

And if we're going to add a new variable, should at least follow the existing pattern here of `num_*`

2022-02-01 19:19 UTC, rowanseymour commented on temba/contacts/models.py
> +        return mappings, num_records, num_ignored
I think fine to just return `num_records` as the number of things we'll try to import and that is already displayed on the import preview page (currently this PR tells them the number of rows included ignored)

2022-02-01 19:48 UTC, norkans7 commented on temba/contacts/models.py
> +        valid_records_count = 0
the way I had understood `num_records` as the row number as it is also later used to indicate the start and end of a batch so if we are skipping some rows the start and end would be wrong and cause mismatch of the rows if we ever relied on the start and end for batch to indicate the row with issues

2022-02-01 19:48 UTC, norkans7 commented on temba/contacts/models.py
> +        valid_records_count = 0
I can rename that to `num_valid_records`

2022-02-01 19:52 UTC, norkans7 commented on temba/contacts/models.py
> +        return mappings, num_records, num_ignored
I have not added the num_ignored on the DB object, we can add that if we really going to display that number in the same way as the `num_records`

2022-02-01 19:52 UTC, norkans7 commented on temba/contacts/models.py
> +        return mappings, num_records, num_ignored
check https://github.com/nyaruka/rapidpro/pull/3666#issuecomment-1023719593

2022-02-01 20:08 UTC, norkans7 commented on temba/contacts/models.py
> +        return mappings, num_records, num_ignored
Same understanding, I will check the batch start and end are using the row numbers properly and adjust the changes needed

2022-02-01 20:16 UTC, rowanseymour commented on temba/contacts/models.py
> +        return mappings, num_records, num_ignored
Hmm I guess there's now no good way to ensure the row numbers are correct now for batches since we're potentially skipping rows within a batch... that kinda sucks but I think I still prefer getting row numbers wrong sometimes in error messages to queueing up junk rows for mailroom to ignore. Maybe we put the row number on the contact spec blob?

2022-02-01 20:23 UTC, norkans7 commented on temba/contacts/models.py
> +        return mappings, num_records, num_ignored
I think we can just the the batch can have 100 records with start 110 and end 215
since the previous batch skipped 10 rows and the current batch skipped another 5

2022-02-01 20:25 UTC, norkans7 commented on temba/contacts/models.py
> +        return mappings, num_records, num_ignored
However the `num_records` I guess should include the skipped rows still on the DB object as currently counted

2022-02-01 20:26 UTC, norkans7 commented on temba/contacts/models.py
> +        return mappings, num_records, num_ignored
I mean as counted on this PR

2022-02-01 20:43 UTC, rowanseymour commented on temba/contacts/models.py
> +        return mappings, num_records, num_ignored
A batch might start on row 110 but it's second record might be row 112 if row 111 is just junk.

I took a look at the mailroom side and actually we want `ContactImportBatch.record_start` and `record_end` to remain as record indexes. I think the simplest solution is adding a field to the contact spec to hold the row number: https://github.com/nyaruka/mailroom/pull/584

That way record always means record rather than row, and error messages can have a record and a row number.

2022-02-01 21:40 UTC, norkans7 commented on temba/contacts/models.py
> +        return mappings, num_records, num_ignored
I added `_import_row` to spec, wondering if we need to match Excel as it start to count from 1
so row 1 has the headers first record is at row 2

currently I have not matched Excel so we are off by 1

2022-02-01 21:52 UTC, rowanseymour commented on temba/contacts/models.py
> +        return mappings, num_records, num_ignored
I don't feel strongly but maybe simplest if row numbers match Excel row numbers since they're only use is for reporting errors back to users

2022-02-02 16:34 UTC, rowanseymour requested changes

2022-02-02 16:34 UTC, rowanseymour commented on temba/contacts/models.py
> +        num_valid_records = 0
records means records so we don't need this distinction now.. I think this method just needs to return `num_records`

2022-02-02 16:34 UTC, rowanseymour commented on temba/contacts/models.py
> +        num_valid_records = 0
`num_records`

2022-02-02 16:34 UTC, rowanseymour commented on temba/contacts/models.py
> +            if num_valid_records % ContactImport.BATCH_SIZE == 0:
I think the way to do this is get rid of `chunk_list` which is splitting on a fixed number of rows - if you want to be clever you could write another generator that yields batches of records

2022-02-04 16:09 UTC, rowanseymour requested changes

2022-02-04 16:09 UTC, rowanseymour commented on temba/contacts/models.py
> +            if num_records % ContactImport.BATCH_SIZE == 0:
`if len(batch_specs) == ContactImport.BATCH_SIZE`

2022-02-04 16:09 UTC, rowanseymour commented on temba/contacts/models.py
> +        init_urns = []
not following what this is needed for

2022-02-04 16:09 UTC, rowanseymour commented on temba/contacts/models.py
> +        return batches, urns
this method kinda defeats the purpose of using the generator since we're now loading all the batches into memory... we want to iterate thru the import file, processing batches as we find them

2022-02-04 16:33 UTC, norkans7 commented on temba/contacts/models.py
> +        init_urns = []
urns are needed to check for detect spamminess and that need the URNs from all rows

2022-02-04 16:36 UTC, norkans7 commented on temba/contacts/models.py
> +        return batches, urns
Ahh right

2022-02-04 17:25 UTC, rowanseymour commented on temba/contacts/models.py
> +        init_urns = []
feels a little odd having this be passed in as a param and modified.. but more importantly.. why do we do the spamminess check after importing? In `try_to_parse` we already grab URNs so shouldn't we do it there? I'm thinking put the spamminess check at the end because originally `try_to_parse` was just parsing headers...

2022-02-04 17:50 UTC, norkans7 commented on temba/contacts/models.py
> +        init_urns = []
I agree on that however do you mean we just flag an account just because the attempted to import the file even before the import happens?

2022-02-07 19:47 UTC, rowanseymour requested changes

2022-02-07 19:47 UTC, rowanseymour commented on temba/contacts/models.py
> +        batches_gen = self._batches_generator(data, urns)
this is still loading all the batches into a single list.. which defeats the purpose of using a generator to allow to iterate over batches

2022-02-07 19:47 UTC, rowanseymour commented on temba/contacts/models.py
> +        record_num = 0
this is the row number no? Can call it `row`

2022-02-10 21:06 UTC, rowanseymour commented on CHANGELOG.md
> + * Add migration to remove inactive contacts from user groups
bad merge ?

2022-02-10 21:55 UTC, rowanseymour commented
@norkans7 fixed the weird merge, tweaked iterating over the generator to just use a for loop, and made it so that record_start and record_end are always the zero-based record indices. The spaminess stuff can stay where it is for now.

2022-02-10 22:02 UTC, rowanseymour commented on temba/contacts/models.py
> +        batches_gen = self._batches_generator(data, urns)
ah ok I didn't realize we already load all the batches into memory anyway because we have to know how many there are before we let them start

2022-02-10 22:02 UTC, rowanseymour approved these changes

2022-02-14 14:26 UTC, merged