use original filename to upload file
nyaruka/rapidpro pull request #3687
Opened 2022-02-15 15:50 UTC by rasoro

changing file path to use original filename at the end instead UUID. 
As discussed here: https://github.com/nyaruka/courier/issues/383

2022-02-15 16:24 UTC, norkans7 commented on temba/flows/views.py
> +                ,)
Why those comma?

2022-02-15 16:26 UTC, norkans7 commented on temba/flows/views.py
> +            uuid = str(uuid4())
may be rename that to `random_uuid_folder_name` instead of just `uuid`

2022-02-15 16:27 UTC, norkans7 requested changes
We need a test as well for that or update the existing tests

2022-02-15 18:52 UTC, rowanseymour commented on temba/flows/views.py
> +            uuid = str(uuid4())
`name_uuid` seemed fine to me...

2022-02-17 00:16 UTC, rasoro commented on temba/flows/views.py
> +                ,)
Sorry it went unnoticed by me, it was because of formatOnSave.
 
Fixed now.

2022-02-17 07:51 UTC, norkans7 requested changes
Run `./code_checks.py`

2022-02-17 14:02 UTC, norkans7 approved these changes

2022-02-17 16:33 UTC, merged