Fix contact release
nyaruka/rapidpro pull request #3689
Opened 2022-02-15 21:46 UTC by norkans7

2022-02-15 21:49 UTC, norkans7 commented on temba/contacts/migrations/0150_full_release_deleted_contacts.py
> +    for contact in deleted_contacts:
copied over the method https://github.com/nyaruka/rapidpro/pull/3689/files#diff-7b90ea5e3fb9ba05a8e735870b6aca87d34d2c41584165c9717416ebdd0a12e2R1163 

And adjusted the `release` method to use the model delete properly

2022-02-15 21:50 UTC, norkans7 commented on temba/contacts/tests.py
> +class FullReleaseDeletedContacts(MigrationTest):
Here I reused the test https://github.com/nyaruka/rapidpro/pull/3689/files#diff-39f3403039114df98053bfecba73c47231022eb2aa652abf6680c2436ba350a4L1447

adjusting the variable with `self.` so I can verify the values after running migration

2022-02-16 15:41 UTC, rowanseymour commented on temba/contacts/migrations/0150_full_release_deleted_contacts.py
> +            ticket.delete()
let's override `delete()` on ticket and have it clear `self.broadcasts.update(ticket=None)` and then call `super().delete()`

2022-02-16 15:42 UTC, rowanseymour commented on temba/contacts/migrations/0150_full_release_deleted_contacts.py
> +            ticket.delete()
although I guess that doesn't work inside the migration right? But in the real `_full_release` it should work

2022-02-16 16:00 UTC, norkans7 commented on temba/contacts/migrations/0150_full_release_deleted_contacts.py
> +            ticket.delete()
Yes that cannot work in the migrations

2022-02-16 16:26 UTC, rowanseymour requested changes

2022-02-16 16:46 UTC, rowanseymour approved these changes

2022-02-16 18:17 UTC, merged