WAC channel
nyaruka/rapidpro pull request #3819
Opened 2022-05-17 12:52 UTC by norkans7

2022-05-26 19:14 UTC, rowanseymour requested changes

2022-05-26 19:14 UTC, rowanseymour commented on temba/channels/types/whatsapp_cloud/tests.py
> +        self.assertTrue(Channel.CONFIG_WHATSAPP_CLOUD_USER_TOKEN in self.client.session)
`self.assertIn`

2022-05-26 19:14 UTC, rowanseymour commented on temba/msgs/models.py
> +    org_limit_key = Org.LIMIT_LABELS
accidental keyboard hit?

2022-05-26 19:14 UTC, rowanseymour commented on temba/request_logs/models.py
> +        secrets = [settings.WHATSAPP_ADMIN_SYSTEM_USER_TOKEN]
This feels like it's in the wrong place. We use this class to represent request logs for all sorts of things, 99% of which won't contain a whatsapp token. So it feels inefficient that we'll look for that in every single request URL, payload and response.

Maybe pass in a list of things to redact as an arg?

2022-05-27 10:26 UTC, norkans7 commented on temba/request_logs/models.py
> +        secrets = [settings.WHATSAPP_ADMIN_SYSTEM_USER_TOKEN]
This method is called in the 3 methods above, I guess we can use a if block here instead to make sure we have the correct list to redact when the log type is one of 
`WHATSAPP_TEMPLATES_SYNCED, WHATSAPP_TOKENS_SYNCED, WHATSAPP_CONTACTS_REFRESHED, WHATSAPP_CHECK_HEALTH`

2022-05-27 10:26 UTC, norkans7 commented on temba/request_logs/models.py
> +        secrets = [settings.WHATSAPP_ADMIN_SYSTEM_USER_TOKEN]
This method is called in the 3 methods above, I guess we can use a if block here instead to make sure we have the correct list to redact when the log type is one of 
`WHATSAPP_TEMPLATES_SYNCED, WHATSAPP_TOKENS_SYNCED, WHATSAPP_CONTACTS_REFRESHED, WHATSAPP_CHECK_HEALTH`

2022-05-27 16:13 UTC, rowanseymour requested changes

2022-05-27 16:13 UTC, rowanseymour commented on temba/request_logs/models.py
> +            if secret and original:
this `if` feels a little unnecessary

2022-05-27 16:13 UTC, rowanseymour commented on templates/channels/types/whatsapp_cloud/claim.haml
> +
less spaces...

2022-05-27 16:13 UTC, rowanseymour commented on temba/channels/models.py
> +                original = redact.text(original, secret, mask)
this again feels pretty weird - this method is used across all channel log types and takes a set of things to redact so why wouldn't we pass `settings.WHATSAPP_ADMIN_SYSTEM_USER_TOKEN` in with those?

also the `if` isn't necessary

2022-05-30 10:31 UTC, norkans7 commented on temba/channels/models.py
> +                original = redact.text(original, secret, mask)
Added the if block above to only use this for WAC channel logs

2022-05-30 16:04 UTC, rowanseymour commented on temba/channels/models.py
> +                original = redact.text(original, secret, mask)
This still doesn't feel right - the whole reason for channel types is that they're pluggable and `temba.channels` doesn't need to know about specific types.

ChannelType already has a `redact_request_keys` and `redact_response_keys`.. maybe it needs `redact_values` as well?

2022-05-30 17:34 UTC, norkans7 commented on temba/channels/models.py
> +                original = redact.text(original, secret, mask)
Added that now in https://github.com/nyaruka/rapidpro/pull/3819/commits/cd64667fa0623f32dc04f508209af848c3b7e5ed

2022-05-30 18:16 UTC, merged