Slack channel
nyaruka/rapidpro pull request #3850
Opened 2022-06-14 13:45 UTC by rasoro

https://github.com/rapidpro/rapidpro/issues/1661

2022-06-15 09:30 UTC, norkans7 commented on temba/channels/types/slack/tests.py
> +        self.channel = self.create_channel(
this is not used at all, I think that can be removed

2022-06-15 09:38 UTC, norkans7 commented on temba/channels/types/slack/views.py
> +
I think we want also to make sure the token is not also used on any other workspace too

2022-06-15 09:39 UTC, norkans7 commented on temba/channels/types/slack/views.py
> +            address=auth_test["user"],
Do bots have some unique IDs we can use as address instead of user ID? Can a user have more that one bot app?

2022-06-15 09:43 UTC, norkans7 commented on temba/channels/types/slack/views.py
> +
I am thinking something like https://github.com/nyaruka/rapidpro/blob/6bf457d11ad470ef84dba51ad8cd0a7bdc63de31/temba/channels/views.py#L615-L636

2022-06-20 18:57 UTC, rasoro commented on temba/channels/types/slack/views.py
> +            address=auth_test["user"],
it could be like this so `address=auth_test["bot_id"]`

this call usually returns this:
```
{
  "ok":true,
  "url":"https:\/\/teste-apigrupo.slack.com\/",
  "team":"teste-api",
  "user":"weni_test",
  "team_id":"T03CN5KTA6S",
  "user_id":"U03JWQ568CA",
  "bot_id":"B03JTSTRD45",
  "is_enterprise_install":false
}
```

2022-06-21 11:54 UTC, norkans7 commented on temba/channels/types/slack/views.py
> +            address=auth_test["user"],
That will be more correct so a user can have even more bots(slack apps) connected

2022-06-28 13:13 UTC, norkans7 commented on temba/channels/types/slack/views.py
> +            value = self.cleaned_data["user_token"]
This existing channel should use the bot_id

2022-06-28 13:15 UTC, norkans7 requested changes
Please address the existing comments as well 

Also have you tested this works, as my test I have not been able to send messages to the bot

2022-06-28 13:17 UTC, norkans7 commented
I tried to have a Slack bot to test but it says I cannot send messages to it
<img width="1118" alt="Monosnap Slack | NyarukaTest | Nyaruka 2022-06-28 15-07-44" src="https://user-images.githubusercontent.com/1040571/176187959-4864e0de-012e-438d-aa48-c24582a9163c.png">

While I have added all the scopes as instructed
<img width="671" alt="Monosnap Slack API: Applications | Nyaruka Slack 2022-06-28 15-07-04" src="https://user-images.githubusercontent.com/1040571/176188202-d6123bec-9340-4649-bd0f-19ead2a2e016.png">
<img width="660" alt="Monosnap Slack API: Applications | Nyaruka Slack 2022-06-28 15-06-35" src="https://user-images.githubusercontent.com/1040571/176188220-c8ce6642-f921-4f7c-bb46-e648915763eb.png">
<img width="701" alt="Monosnap Slack API: Applications | Nyaruka Slack 2022-06-28 15-06-17" src="https://user-images.githubusercontent.com/1040571/176188239-496d8a4e-15b2-418b-9a7c-7825b1ee5539.png">
<img width="682" alt="Monosnap Slack API: Applications | Nyaruka Slack 2022-06-28 15-06-04" src="https://user-images.githubusercontent.com/1040571/176188243-1f8798d4-0e5a-4f5f-aa95-e27b3e2fb399.png">

2022-06-30 21:43 UTC, rasoro commented
![2022-06-30_17-51-37](https://user-images.githubusercontent.com/75167930/176783904-46c6bd76-53cb-4a3c-bb4a-759440a369f9.png)

some tests I did.

2022-06-30 21:47 UTC, rasoro commented
hi @norkans7 , what do you think of the settings screen this way?

![2022-06-30_18-40-23](https://user-images.githubusercontent.com/75167930/176784023-b797a28d-9124-4a64-ba02-3c4d44350884.png)

2022-07-05 08:49 UTC, norkans7 commented on temba/channels/types/slack/views.py
> +            existing = Channel.objects.filter(
I think it is useful to the users to clarify when the channel is used on the same workspace or on a different workspace as most get confused on which workspace they had added that.

Check again https://github.com/nyaruka/rapidpro/pull/3850#discussion_r897768334

2022-07-05 08:54 UTC, norkans7 commented
@rasoro the configuration screen looks better now, can you mention a step to install the bot to a Slack workspace too?

2022-07-05 08:57 UTC, norkans7 requested changes
Few adjustments for better error feedback for existing channels

2022-07-14 20:49 UTC, rasoro commented on temba/channels/types/slack/views.py
> +            existing = Channel.objects.filter(
check if it can be as it is now, please.

2022-07-19 11:34 UTC, norkans7 approved these changes

2022-07-22 15:48 UTC, rowanseymour requested changes

2022-07-22 15:48 UTC, rowanseymour commented on temba/channels/types/slack/views.py
> +                    raise ValidationError(_("A slack channel for this bot already exists in this organization."))
we're probably not very consistent about this but use `workspace` in the UI, and `org` in code

2022-07-22 15:48 UTC, rowanseymour commented on temba/channels/types/slack/views.py
> +                "In https://api.slack.com/apps select your bot app and go to Features / OAuth & Permissions to see this information."
Can these be actual links that open in new window

2022-07-22 15:48 UTC, rowanseymour commented on temba/channels/types/slack/views.py
> +                "In https://api.slack.com/apps select your bot app and go to Features / OAuth & Permissions to see this information."
Or just simplify to `In Slack select your bot app and go to Features / OAuth & Permissions to see this information.`

2022-08-01 14:59 UTC, Robi9 commented
@rasoro won't be available in the next few days so I'll be responsible for the changes that are requested in this PR, but could you take a look at the changes he's already added here? @rowanseymour

2022-08-02 14:51 UTC, rowanseymour requested changes

2022-08-02 14:51 UTC, rowanseymour commented on temba/contacts/models.py
> +        (SLACK_SCHEME, _("Slack Identifier")),
let's keep these alphabetical (tel first is the only exception)

2022-08-02 14:51 UTC, rowanseymour commented on temba/channels/types/slack/type.py
> +    category = ChannelType.Category.SOCIAL_MEDIA
@ericnewcomer @norkans7 do things like Slack, RocketChat, Teams fit in social media? Are they possibly something different?

2022-08-02 14:51 UTC, rowanseymour commented on templates/channels/types/slack/config.haml
> +      When Messages Tab is activated, will appear a checkbox, so check it to (Allow users to send Slash commands and messages from the messages tab).
`When the Messages Tab is activated a checkbox will appear, check it to allow users to send Slash commands and messages.`

2022-08-02 15:09 UTC, norkans7 commented on temba/channels/types/slack/type.py
> +    category = ChannelType.Category.SOCIAL_MEDIA
Probably we make new categories with `Messaging Platforms`, `Chat Apps` and `Social Network` channels

2022-08-03 19:51 UTC, Robi9 commented on temba/channels/types/slack/type.py
> +    category = ChannelType.Category.SOCIAL_MEDIA
Do I leave it as `Social Media`?

2022-08-03 19:59 UTC, rowanseymour commented on temba/channels/types/slack/type.py
> +    category = ChannelType.Category.SOCIAL_MEDIA
@Robi9 yeah that's fine for now

2022-09-13 14:59 UTC, matmsa27 commented
Hey @rowanseymour @norkans7 can we move on with this PR?

2022-09-13 15:53 UTC, rowanseymour commented
@matmsa27 I think this is good to go.. am a bit confused tho because it's saying above that the checks haven't completed and there are conflicts that need resolved... but I don't see any CI jobs running and it's not listing the conflicts.. github having problems again?

2022-09-13 21:38 UTC, rowanseymour commented
@Robi9 @matmsa27 maybe try pushing to this branch and see if it kicks off the CI checks? They seem to be stuck.

2022-09-14 14:47 UTC, merged