📣 ❌ Ability to delete broadcasts
nyaruka/rapidpro pull request #4021
Opened 2022-09-29 09:03 UTC by susanm74

2022-09-29 09:05 UTC, susanm74 commented on temba/msgs/views.py
> +        # todo need to figure out why this is not displaying
can't quite figure out why this isn't displaying on the frontend yet

2022-09-29 09:08 UTC, susanm74 commented on templates/msgs/broadcast_scheduled_update.haml
wasn't quite sure how to proceed here, so went with the 3rd option for now, as the delete and update seem to have a lot of overlap in terms of ux, so erring on the side of reuse and keeping things DRY:
- create a broadcast_scheduled_delete.haml that copies most of the broadcast_scheduled_update.haml file
- create a broadcast_scheduled_delete.haml that extends the broadcast_scheduled_update.haml file
- (re)use the broadcast_scheduled_update.haml file and don't create an additional broadcast_scheduled_delete.haml
but if it's preferred to create a separate dedicated broadcast_scheduled_delete.haml, let me know!

2022-09-29 09:29 UTC, susanm74 commented on temba/msgs/views.py
> +        # todo list view bulk delete action
to uncomment and work on these list view changes once the entity view changes are done

2022-09-29 10:48 UTC, norkans7 commented on templates/msgs/broadcast_scheduled_update.haml
I think the correct way is to extend a template and then overwrite the block you need to update

2022-09-30 01:22 UTC, ericnewcomer commented on templates/msgs/broadcast_scheduled_update.haml
I'm not sure you even need a template. There is a default behavior for delete views with confirmations. I think this is how the Flow deletion on the editor page works as an example. It just defines the view with minimal configuration and it just works.

2022-09-30 01:24 UTC, ericnewcomer commented on templates/msgs/broadcast_scheduled_update.haml
The list page with bulk deletes is a different ball of wax, and for that case, we probably want to do that confirmation client side (look at selected archived contacts and clicking delete  as an example for that one)

2022-10-03 07:09 UTC, susanm74 commented on temba/msgs/views.py
> +                    reverse("msgs.broadcast_delete", args=[obj.id]),
passing the id here because broadcasts don't have a uuid - do we need to add a uuid to broadcasts?

2022-10-03 07:09 UTC, susanm74 commented on temba/msgs/views.py
> +        cancel_url = "id@msgs.broadcast_scheduled_read"
passing the id here because broadcasts don't have a uuid - do we need to add a uuid to broadcasts?

2022-10-06 09:06 UTC, susanm74 commented
still leaving in draft for now as i'm working on unit tests, but if someone gets a chance to look at the changes so far would love any feedback so that i can push any updates when i push testing updates

2022-10-06 13:07 UTC, rowanseymour requested changes

2022-10-06 13:07 UTC, rowanseymour commented on temba/flows/models.py
> +    broadcast_dependencies = models.ManyToManyField(Broadcast, related_name="dependent_flows")
not needed, flows can't depend on broadcasts

2022-10-06 13:07 UTC, rowanseymour commented on temba/msgs/migrations/0193_delete_broadcastcrudl.py
> +    ]
not even sure hpw this got generated...

2022-10-06 13:07 UTC, rowanseymour commented on temba/msgs/models.py
> +class Broadcast(models.Model, DependencyMixin):
remove `DependencyMixin`

2022-10-06 13:07 UTC, rowanseymour commented on temba/msgs/models.py
> +        return super().get_dependents()
remove

2022-10-06 13:07 UTC, rowanseymour commented on temba/msgs/views.py
> +class BroadcastCRUDL(SmartCRUDL, DependencyMixin):
this is a mixin for models, not views

2022-10-06 13:07 UTC, rowanseymour commented on temba/msgs/views.py
> +        # todo list view bulk delete action
forget about BulkAction deletes for now (i.e. checkboxes) and just make this PR a delete button on scheduled broadcast read page

2022-10-06 13:07 UTC, rowanseymour commented on temba/msgs/views.py
> +    class Delete(DependencyDeleteModal):
Just use `OrgObjPermsMixin` and `SmartDeleteView`

2022-10-06 13:07 UTC, rowanseymour commented on temba/msgs/views.py
> +        cancel_url = "id@msgs.broadcast_scheduled_read"
this should be fine

2022-10-06 13:07 UTC, rowanseymour commented on temba/orgs/views.py
> +        )
not needed

2022-10-06 13:07 UTC, rowanseymour commented on temba/orgs/views.py
> +        obj.release()
undo

2022-10-06 13:07 UTC, rowanseymour commented on temba/settings_common.py
> +        "delete",
call this view `scheduled_delete` since it only applies to scheduled broadcasts - i.e. the class name will be `ScheduledDelete`

2022-10-06 13:07 UTC, rowanseymour commented on templates/orgs/dependency_delete_modal.haml
> +      {{ display_name }}.
undo these..

2022-10-10 03:39 UTC, closed without merging