📣 ❌  delete broadcasts mulligan
nyaruka/rapidpro pull request #4039
Opened 2022-10-10 05:25 UTC by susanm74

- added scheduled_delete to permissions and ran migrations
- added build content menu delete item with modax
- added broadcast crudl scheduled delete class to load delete content into modax

todo
- before delete, modal should display truncated version of object string vs. "You are about to delete **Broadcast[id=25, text={'base': 'blah blah blah'}]**. There is no way to undo this. Are you sure?"
- after delete, modal should close, currently it's staying open and displaying scheduled messages list content inside of it with an ok button
- after delete, scheduled messages list page should display with the updated list and the left side bar "Scheduled" item count should be decremented by one, currently the modal staying open is preventing both of these things
- unit testing

2022-10-10 11:56 UTC, norkans7 commented on temba/msgs/tests.py
> +        response = self.client.get(delete_url)
Remove the debug line that are commented out

2022-10-10 11:57 UTC, norkans7 commented on temba/msgs/tests.py
> +        self.assertEqual("/broadcast/scheduled/", response["Temba-Success"])
We also need to assert that no broadcast with the `broadcast.id` still exist and same for the schedule with `schedule.id`

2022-10-10 11:58 UTC, norkans7 requested changes
a couple of changes for the tests

2022-10-11 05:33 UTC, susanm74 commented
<img width="1725" alt="Screen Shot 2022-10-11 at 12 33 06 PM" src="https://user-images.githubusercontent.com/854012/195004896-6ffe8cdf-31af-4dbf-9e52-85710806f007.png">

2022-10-11 05:34 UTC, susanm74 commented
<img width="1723" alt="Screen Shot 2022-10-11 at 12 33 27 PM" src="https://user-images.githubusercontent.com/854012/195004926-7eface00-2434-4add-9293-cedfcc0ff494.png">

2022-10-11 05:41 UTC, susanm74 commented
how do we feel about the way the Broadcast object displays in the modal? let me know if we should customize this to be a bit cleaner for users (ex. i think users refer to these entities as "scheduled messages" and not "broadcasts", yeah? or do they refer to them using either name?)

2022-10-11 06:05 UTC, susanm74 commented
also, if the scheduled message has been sent at least once before being deleted, does deleting risk creating an orphan if there's a FK referring to a Broadcast that doesn't exist anymore? (ex. Msg and BroadcastMsgCount) i noticed these FKs are defined to PROTECT on_delete, but when i schedule a message, send it once, and then delete the scheduled message, i noticed that it lets me delete it, and it also deletes the sent message, and decrements the sent messages total - is this how we expect deleting a scheduled message should behave? or should this scenario disallow a scheduled message from being deleted?

2022-10-11 09:42 UTC, susanm74 commented
OLD INTERFACE
<img width="739" alt="Screen Shot 2022-10-11 at 4 18 06 PM" src="https://user-images.githubusercontent.com/854012/195056092-5c3f3cfb-0ef4-4544-a7fc-447bed46788a.png">
<img width="758" alt="Screen Shot 2022-10-11 at 4 18 17 PM" src="https://user-images.githubusercontent.com/854012/195056116-b765d020-65ff-4290-a3fa-b7d704fb0f70.png">

2022-10-11 09:43 UTC, susanm74 commented
NEW INTERFACE
<img width="1725" alt="Screen Shot 2022-10-11 at 4 18 42 PM" src="https://user-images.githubusercontent.com/854012/195056266-7e1c0079-1181-4a79-b93a-86fa2ed18e85.png">

2022-10-11 10:02 UTC, susanm74 commented
> also, if the scheduled message has been sent at least once before being deleted, does deleting risk creating an orphan if there's a FK referring to a Broadcast that doesn't exist anymore? (ex. Msg and BroadcastMsgCount) i noticed these FKs are defined to PROTECT on_delete, but when i scheduled a message, sent it once, and then deleted the scheduled message, i noticed that it lets me delete it, and it also deletes the sent message, and decrements the sent messages total - is this how we expect deleting a scheduled message should behave? or should this scenario disallow a scheduled message from being deleted?

was going to shift this out of draft mode, but i want to be sure this scenario is being handled correctly...
@norkans7 pointed out that the release method is kind of bypassing the FK stuff and deleting all of the children, msgs, broadcastMsgCount, schedules, etc are being deleted before deleting the broadcast itself - is this the behavior we want? i think i see 3 options:
1. use the existing logic the way it is, although i could see this being confusing to a user to have sent messages suddenly disappear after deleting a scheduled message, but i'm not sure if there's an easy way to keep them around without keeping the broadcast around
2. make it super duper clear using language in the delete modal and specify what else will get deleted when a broadcast is deleted
3. update the logic to somehow archive or deactivate or hide the broadcast from the list of scheduled messages, but don't actually delete it

2022-10-13 02:06 UTC, susanm74 commented
@ericnewcomer @rowanseymour a gentle nudge here...

2022-10-17 06:22 UTC, susanm74 commented
closing in favor of:
- PR#1 - https://github.com/nyaruka/rapidpro/pull/4056
- PR#2 - TBD
- PR#3 - https://github.com/nyaruka/rapidpro/pull/4059
- PR#4 - https://github.com/nyaruka/rapidpro/pull/4057
- PR#5 - https://github.com/nyaruka/rapidpro/pull/4058

2022-10-17 06:22 UTC, closed without merging