delete broadcasts - PR#1
nyaruka/rapidpro pull request #4056
Opened 2022-10-17 05:39 UTC by susanm74

2022-10-17 13:47 UTC, rowanseymour requested changes

2022-10-17 13:47 UTC, rowanseymour commented on temba/msgs/migrations/0194_broadcast_is_active.py
> +            field=models.BooleanField(default=True, null=True),
Can't add the default in this step otherwise django will try to update every existing row with `is_active=True`. If you run `./manage sqlmigrate msgs 0194` it'll show you the SQL that would be run for this migration and you'll see an `UPDATE` like that. One of our databases has 7 million rows in this table which would require a longer lock than we can do. So what we do is.. a

1. Add it without the default..

```
is_active = models.BooleanField(null=True)
```

2. Run `makemigrations`..
3. Add the default

```
is_active = models.BooleanField(null=True, default=True)
```

4. Run `makemigrations`..
5. (Optional for tidyness) manually move the operation from the second migration file into the first migration file so we have a single migration with 2 operations - the `AddField` and the `AlterField`.

What that will give you is a migration which adds a nullable field and starts setting it for new rows. We can worry about the existing rows later in a data migration that updates them in batches.

2022-10-17 14:51 UTC, susanm74 commented on temba/msgs/migrations/0194_broadcast_is_active.py
> +            field=models.BooleanField(default=True, null=True),
@rowanseymour ah cool, makes sense, will update this PR with the above

2022-10-18 14:20 UTC, rowanseymour commented on temba/msgs/tests.py
> +        self.assertEqual(True, broadcast1.is_active)
don't forget there's a `self.assertTrue(..)`

2022-10-18 14:20 UTC, rowanseymour approved these changes

2022-10-18 14:20 UTC, merged