delete broadcasts PR#5
nyaruka/rapidpro pull request #4058
Opened 2022-10-17 06:13 UTC by susanm74

2022-10-20 15:04 UTC, rowanseymour requested changes

2022-10-20 15:04 UTC, rowanseymour commented on temba/msgs/tests.py
> +    def test_scheduled_deactivate(self):
just use `delete` as the verb - we consider setting `is_active=False` a soft delete

2022-10-20 15:04 UTC, rowanseymour commented on temba/msgs/views.py
> +    class ScheduledDeactivate(ModalMixin, OrgObjPermsMixin, SmartDeleteView):
ScheduledDelete

2022-10-20 15:04 UTC, rowanseymour commented on temba/msgs/views.py
> +            context["object_name"] = truncate(self.object.get_text(), 15)
don't try to give it a name - just confirm with..

```
You are about to delete this scheduled message. There is no way to undo this. Are you sure?
```

2022-10-20 15:04 UTC, rowanseymour commented on temba/msgs/views.py
> +        object_name = ""
remove

2022-10-20 16:40 UTC, rowanseymour commented on temba/msgs/views.py
> +            broadcast.save()
Good practice to use `update_fields` except where there are too many fields, so...

```
broadcast.save(update_fields=("is_active",))
```

2022-10-21 14:13 UTC, rowanseymour requested changes

2022-10-21 14:13 UTC, rowanseymour commented on templates/msgs/broadcast_scheduled_delete.haml
> +      %span.font-normal
don't need this formatting.. just..

```
You are about to delete this scheduled message. There is no way to undo this. Are you sure?
```

2022-10-21 14:13 UTC, rowanseymour commented on temba/msgs/views.py
> +        # we create a frontend "delete" ux, but we actually just do a backend update
don't need this comment - it's generally how deletes are done

2022-10-21 14:13 UTC, rowanseymour commented on temba/tests/crudl.py
> +                return self.requestView(url, user, checks=checks, HTTP_X_PJAX=True)
is this needed?

2022-10-21 14:34 UTC, rowanseymour commented on temba/msgs/models.py
> +    # todo figure out if this is how to update the scheduled messages count in the left side nav bar
clean up

2022-10-21 16:23 UTC, norkans7 commented on temba/msgs/views.py
> +            broadcast.save(update_fields=("is_active",))
I guess we need to update `modified_on` too, probably `modified_by` as well

2022-10-24 07:24 UTC, susanm74 commented on temba/tests/crudl.py
> +                return self.requestView(url, user, checks=checks, HTTP_X_PJAX=True)
@rowanseymour yeah, @ericnewcomer and i did some troubleshooting on this, and my understanding is that for tests, the view is not returned as a modal by default, so we needed to add this for tests that need the view to be returned as a modal

2022-10-24 14:10 UTC, merged