delete broadcasts PR#3
nyaruka/rapidpro pull request #4059
Opened 2022-10-17 06:16 UTC by susanm74

2022-10-18 15:46 UTC, rowanseymour commented
@susanm74 so usually for a data migration I'd insist on a unit test (saerch thru the code for instances of `MigrationTest`) but we can make an exception for this since it's so simple.

2022-10-18 15:47 UTC, rowanseymour commented
Although having said that... it doesn't appear to be right hehehe

2022-10-18 15:52 UTC, rowanseymour requested changes

2022-10-18 15:52 UTC, rowanseymour commented on temba/msgs/migrations/0195_update_broadcast_is_active.py
> +        print(f"Updated {num_updated} broadcasts without an is_active")
Ok so what this migration will do is.. enter the `while`, fetch 1000 broadcasts, update their is_active to `True`, fetch... the same 1000 broadcasts (most likely, there's no gaurantee which 1000 broadcasts it will fetch), update the same 1000 broadcasts, repeat forever.

Let's tweak it to...

```python
batch_ids = list(Broadcast.objects.filter(is_active=None).values_list("id", flat=True)[:5000])

if not batch_ids:
    break

Broadcast.objects.filter(id__in=batch_ids).update(is_active=True)
```

That way we always fetch only broadcasts that need updating, and we only fetch ids - more performant than fetching entire `Broadcast` objects.

2022-10-19 04:13 UTC, susanm74 commented on temba/msgs/migrations/0195_update_broadcast_is_active.py
> +        print(f"Updated {num_updated} broadcasts without an is_active")
@rowanseymour ah, this totally makes sense, i didn't realize this risk with using filter, and (incorrectly) assumed it just grabs the "next" batch, so will fix that, and also totally down to add a migration unit test

2022-10-19 11:02 UTC, norkans7 commented on temba/msgs/migrations/0195_update_broadcast_is_active.py
> +
I think you can add the method `apply_manual` which will allow us to apply the migration after faking it so we run that in the background when the services are up and running

2022-10-19 11:04 UTC, norkans7 commented on temba/msgs/migrations/0195_update_broadcast_is_active.py
> +
https://github.com/nyaruka/rapidpro/blob/419f9144bb86c947fbfd206929cf83c9600739c6/temba/ivr/migrations/0021_convert_connections.py#L56

2022-10-19 13:24 UTC, rowanseymour approved these changes

2022-10-19 13:29 UTC, merged

2022-10-20 03:49 UTC, susanm74 commented on temba/msgs/migrations/0195_update_broadcast_is_active.py
> +
@norkans7 ooh, good to know, hopefully will be able to make use of this for future migrations, thank you!