🛀 Remove topups part 2
nyaruka/rapidpro pull request #4075
Opened 2022-10-20 18:41 UTC by rowanseymour

* Removes creating, updating and managing topups
 * Removes the transfer credits view

2022-10-20 20:16 UTC, norkans7 commented on temba/settings_common.py
> -    "orgs.topup": ("manage",),
`orgs.topup` line should be removed here entirely

2022-10-20 20:20 UTC, norkans7 requested changes
just the 2 changes

2022-10-21 06:20 UTC, susanm74 approved these changes
LGTM 👍

2022-10-21 14:05 UTC, rowanseymour commented on temba/settings_common.py
> -    "orgs.topup": ("manage",),
Ah I was thinking that would remove the read/list permissions for the views I'm leaving for now

2022-10-21 14:40 UTC, merged