🍔  new content menu
nyaruka/rapidpro pull request #4192
Opened 2022-12-09 02:40 UTC by susanm74

https://github.com/nyaruka/temba-components/issues/217

2022-12-13 04:09 UTC, susanm74 commented on templates/contacts/contact_list_spa.haml
> +        %form#search-form(method="get" onsubmit="handleSearchSubmitted(event)")
@ericnewcomer this was my initial attempt to handle when there's a page containing both a search form and a content menu, and i wasn't sure if the search-form's onsubmit event was the best/right one to hook into, but when i tried hooking a `-temba-...` custom event type (i tried adding content-changed, loaded, refreshed, submitted, etc) to either the search-form or the temba-textinput element, i found that the handleSearchSubmitted fn was never getting called, but adding it to the search-form's onsubmit worked

2022-12-13 04:18 UTC, susanm74 commented on templates/contacts/contact_list_spa.haml
> +    function handleSearchSubmitted(event){
@ericnewcomer and then here's the `handleSearchSubmitted` fn in which i found some code doing something similar here https://github.com/nyaruka/rapidpro/blob/main/templates/spa_frame.haml#L542 to grab the search param from the form data and add it to the content menu endpoint

2022-12-13 06:47 UTC, susanm74 commented on templates/contacts/contact_list_spa.haml
> +        %form#search-form(method="get" onsubmit="handleSearchSubmitted(event)")
marking this as resolved in favor of using [this](https://github.com/nyaruka/rapidpro/pull/4198/files#r1046711575) comment on a separate draft PR

2022-12-13 06:47 UTC, susanm74 commented on templates/contacts/contact_list_spa.haml
> +    function handleSearchSubmitted(event){
marking this as resolved in favor of using [this](https://github.com/nyaruka/rapidpro/pull/4198/files#r1046711909) comment on a separate draft PR

2022-12-14 07:25 UTC, susanm74 commented
@ericnewcomer notwithstanding the ci/test failure, this is RFR

2022-12-14 10:22 UTC, susanm74 commented on temba/orgs/tests.py
> +        self.assertTrue("Edit Workspace" in str(response.context))
"Edit Workspace" is contained in the response.context, NOT the response.content, but the .assertContains fn only checks response.streaming_content, response.content, and response.charset, so switched this to an assertTrue to instead check for "Edit Workspace" in the context

2022-12-15 08:43 UTC, susanm74 commented
@ericnewcomer this is RFR again!

2022-12-22 07:49 UTC, susanm74 commented
@ericnewcomer this is RFR

2022-12-22 09:24 UTC, susanm74 commented
@ericnewcomer hmm, looks like there's a missing django.template.exceptions.TemplateDoesNotExist: components-head.html that's causing a lot of build errors/failures - i didn't encounter this locally, but when i checked, i noticed that there's an existing components-head.html file in the temba-componentts repo, but no components-head.html file in this repo - any ideas how to resolve this?

2023-01-05 19:57 UTC, rowanseymour commented on temba/archives/tests.py
> +        self.assertContentMenu(runs_url, self.admin, [], True)
this would read better as `is_spa=True` which you can enforce by changing the signature of `assertContentMenu` to use `*, `

2023-01-05 19:57 UTC, rowanseymour commented on package.json
> +    "@nyaruka/flow-editor": "1.19.0
oops

2023-01-06 02:09 UTC, ericnewcomer commented
@susanm74 I fixed the issue with the temba-components release but this PR is still failing for another reason. I also updated things to reflect @rowanseymour's comments above but you should review those changes too.

Can you take a look?
https://github.com/nyaruka/rapidpro/actions/runs/3851131169/jobs/6562007407#step:15:2791

2023-01-06 15:18 UTC, rowanseymour requested changes

2023-01-06 15:18 UTC, rowanseymour commented on temba/tests/crudl.py
> +        self.assertTrue(label in items)
```python
self.assertIn(label, items)
```

2023-01-06 15:18 UTC, rowanseymour commented on temba/tests/crudl.py
> +        self.assertTrue(label not in items)
```python
self.assertNotIn(label, items)
```

2023-01-06 15:18 UTC, rowanseymour commented on temba/tests/crudl.py
> +    def assertContentMenu(self, url: str, user, labels: list, is_spa: bool = False):
`label: str, *, is_spa: bool` if you want to enforce using kwargs

2023-01-06 15:18 UTC, rowanseymour commented on temba/archives/tests.py
> +        self.assertContentMenu(runs_url, self.admin, [], is_spa=True)
not so important, but maybe nicer to make it one call?

```python
self.assertContentMenu(runs_url, self.admin, ["Message Archives"], spa=[])
```

2023-01-06 15:18 UTC, rowanseymour commented on temba/utils/views.py
> +        return menu_items
adding variables isn't improving anything here, please undo

2023-01-06 15:18 UTC, rowanseymour commented on temba/utils/views.py
> +            return JsonResponse({"items": content_menu_items})
as above

2023-01-06 15:18 UTC, rowanseymour commented on temba/utils/views.py
> +        context["has_content_menu"] = has_content_menu
```python
context["has_content_menu"] = len(self._get_content_menu()) > 0
```

2023-01-06 15:18 UTC, rowanseymour commented on temba/utils/views.py
> +            context["has_search_query"] = search_query
```python
context["has_search_query"] = urlencode({"search": self.request.GET["search"]})
```

2023-01-09 07:30 UTC, susanm74 commented on temba/channels/types/whatsapp/tests.py
> +            "Goodbye {{1}}",
note: changing this to be more unique to prevent duplicate template translation content value from causing this test to unexpectedly start failing

2023-01-09 08:22 UTC, susanm74 commented
@ericnewcomer @rowanseymour @norkans7 sweet, looks like the build's passing now 😎 but when i dig into the codecov report, i'm noticing that when i click on the files it indicates went down in coverage, i'm only seeing a single blank line highlighted like this:

<img width="967" alt="Screen Shot 2023-01-09 at 3 20 48 PM" src="https://user-images.githubusercontent.com/854012/211265558-6c655aba-84ba-4a4b-af33-4b57a07f9986.png">

let me know if there's anything i can do to help resolve this!

2023-01-09 13:30 UTC, norkans7 commented
About coverage, still no files on https://app.codecov.io/gh/nyaruka/rapidpro/pull/4192 ?

2023-01-09 14:30 UTC, rowanseymour commented on temba/channels/types/whatsapp/tests.py
> +            "Goodbye {{1}}",
ha I've been trying to ignore that intermittently failing test - you get a prize if this fixes it

2023-01-09 14:33 UTC, rowanseymour commented on templates/spa_page_header.haml
> +-if title or has_content_menu
thid is fine for this PR but I think maybe worth reworking things later so that we don't have to try to build the menu twice - once to know if there will be a menu on the page, a second time when it's actually being fetched @ericnewcomer

2023-01-09 21:45 UTC, rowanseymour commented
@susanm74 https://app.codecov.io/gh/nyaruka/rapidpro/pull/4192 lists the missing files/lines. I think what is happening is that some tests were fetching the normal page view for a URL, and are now only fetching the menu view for that URL. It would suggest those aren't very good tests, but I think you can just ensure they still request the normal page view and assert something about it.

2023-01-10 08:13 UTC, susanm74 commented on temba/channels/types/whatsapp/tests.py
> +            "Goodbye {{1}}",
oh the prize should def go to @norkans7 if this fixes it, as he helped me troubleshoot and suggested this might be the issue

2023-01-10 14:24 UTC, rowanseymour commented on temba/channels/types/whatsapp/tests.py
> +            "Goodbye {{1}}",
I merged this specific change into main because we need it yesterday

2023-01-10 17:37 UTC, ericnewcomer commented
@susanm74 this is still missing a tiny bit of coverage and has a conflict to resolve. lets button this up!

2023-01-11 07:30 UTC, susanm74 commented
@ericnewcomer @rowanseymour @norkans7 RFR

2023-01-11 07:41 UTC, norkans7 approved these changes
Looks good to me

2023-01-18 18:55 UTC, merged