Twilio update
nyaruka/rapidpro pull request #4275
Opened 2023-01-30 14:04 UTC by norkans7

2023-01-30 14:37 UTC, rowanseymour commented on temba/channels/models.py
> +    def check_credentials(self, cleaned_data):
I think we want something more like...

```python
def check_credentials(self, config: dict) -> bool:
```

so then we have something like this on `Channel`

```python
def check_credentials(self) -> bool:
    return self.type.check_credentials(self.config)
```

and then at any time you can verify the credentials of a channel

2023-01-30 15:11 UTC, norkans7 commented on temba/channels/models.py
> +    def check_credentials(self, cleaned_data):
ok

2023-01-30 15:51 UTC, norkans7 commented on temba/channels/types/twilio/views.py
> +        self.add_config_field(
I exatended the channel update to include the credentials field for for the channel type

2023-01-30 15:52 UTC, norkans7 commented on temba/channels/types/twilio/views.py
> +        return self.cleaned_data
We need to clean the credentials, and in case of Twilio we need to save the primary token of the account in case we were given others

So each channel type update form will do its own validation if neeeded

2023-01-30 16:01 UTC, norkans7 commented on temba/channels/models.py
> +    verify_credentials = False
For now we'll be switching this flag once we have added the channel type `check_credentials `

2023-01-31 16:54 UTC, rowanseymour requested changes

2023-01-31 16:54 UTC, rowanseymour commented on temba/channels/types/twilio/views.py
> +                label=_("Your Twilio Account SID"),
Remove `Your `

2023-01-31 16:54 UTC, rowanseymour commented on temba/channels/types/twilio/views.py
> +                label=_("Your Twilio Account Auth Token"),
Remove `Your `

2023-01-31 16:54 UTC, rowanseymour commented on temba/channels/types/twilio/views.py
> +        try:
We want to use `check_credentials` here as well - calling it with the config + these new values, e.g.

```python
self.instance.check_credentials({**self.instance.config, "account_sid": account_sid, "auth_token": auth_token})
```

2023-01-31 16:54 UTC, rowanseymour commented on temba/channels/views.py
> +    def clean(self) -> Dict[str, Any]:
python 3.10 prefers `dict[str, Any]`.. we need to come up with a style guide for typing in Python. I've generally avoided complex types and probably would have just used `dict` here, but we need some rules to keep ourselves consistent.

2023-01-31 16:54 UTC, rowanseymour commented on temba/channels/models.py
> +    verify_credentials = False
could we just have `ChannelType.check_credentials` default to `True` ?

2023-01-31 17:11 UTC, norkans7 commented on temba/channels/types/twilio/views.py
> +        try:
the main thing here is we want to grab the primary credentials so `check_credentials` is not enough alone

otherwise we would have relied on the base class clean from that use the method that way

https://github.com/nyaruka/rapidpro/pull/4275/files#diff-6aff4c43504e1e48908ece639cb7e6a4d98608c0ce761fc2bfd298b10a57ddedR674-R680

2023-01-31 17:12 UTC, norkans7 commented on temba/channels/models.py
> +    verify_credentials = False
I thought we'll remove the flag once the method is implemented for all channel type we have but I guess that is fine to have that default to True

2023-01-31 17:15 UTC, rowanseymour commented on temba/channels/views.py
> +            raise ValidationError(_("Error checking credentials for channel type %s" % self.object.channel_type))
This should be a user facing error message like `Channel credentials don't appear to be valid.`

2023-02-28 06:53 UTC, susanm74 reviewed
@norkans7 i don't know this area of the product super well, so just dropping a comment (vs approving) after reviewing the changes to say LGTM

2023-03-07 16:32 UTC, norkans7 commented
@rowanseymour @ericnewcomer when you get a chance please review

2023-03-07 17:03 UTC, rowanseymour requested changes

2023-03-07 17:03 UTC, rowanseymour commented on temba/channels/types/twilio/views.py
> +    def clean(self) -> Dict[str, Any]:
```python
def clean(self) -> dict[str, Any]:
    """
    We override the clean method for Twilio we need to make sure we grab the primary auth tokens
    """
```

2023-03-08 18:02 UTC, norkans7 commented
The keys are not the same

On Wed, Mar 8, 2023, 8:00 PM Rowan Seymour ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In temba/channels/views.py
> <https://github.com/nyaruka/rapidpro/pull/4275#discussion_r1129643369>:
>
> > @@ -424,6 +425,21 @@ def add_config_field(self, config_key: str, field, *, default):
>          self.fields[config_key] = field
>          self.config_fields.append(config_key)
>
> +    def creds_config(self, cleaned_data: dict, extra: dict) -> dict:
> +        """
> +        Transform form data credentials to config format dict
> +        """
> +        config = cleaned_data.copy()
> +        config.update(**extra)
> +        return config
> +
> +    def clean(self) -> dict[str, Any]:
> +        cleaned_data = super().clean()
> +        credentials_config = self.creds_config(cleaned_data, {})
>
> Am still confused by this line which is just cloning cleaned_data
>
> Shouldn't this be self.object.config | cleaned_data ? i.e. merge existing
> config and new values from form?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/nyaruka/rapidpro/pull/4275#pullrequestreview-1330930588>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAH6BO2HQD3N4U5UICIAWMDW3DCL5ANCNFSM6AAAAAAULGCU4E>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-03-08 22:42 UTC, rowanseymour commented on temba/channels/views.py
> +        credentials_config = self.creds_config(cleaned_data, {})
The idea is that channel types subclass this and override `creds_config`?

In which case make it something like...

```
def to_config(self, data) -> dict:
    return {}
```

That just returns form data transformed into config values, and do the merging in `clean` and `form_valid` with `self.instance.config | self.to_config(cleaned_data)`

2023-03-10 12:43 UTC, norkans7 commented on temba/channels/views.py
> +        credentials_config = self.creds_config(cleaned_data, {})
Right the idea is to allow the subclass to override that in case the form fields names do not match the config keys.
For Twilio so far added I see I had changed to have them match so I think the `to_config` is probably not needed for now.

2023-03-13 16:46 UTC, merged