Make sure WA numbers are claimed once
nyaruka/rapidpro pull request #4288
Opened 2023-02-03 17:52 UTC by norkans7

2023-02-03 19:24 UTC, rowanseymour requested changes

2023-02-03 19:24 UTC, rowanseymour commented on temba/channels/types/whatsapp/views.py
> +        org = self.request.org
is it normal to do validation inside `form_valid` ?

2023-02-03 19:24 UTC, rowanseymour commented on temba/channels/types/whatsapp/views.py
> +            return self.form_invalid(form)
I think this logic would be simpler if it were..

1. Look for a channel across all orgs
2. If existing.org = org then show error message 1, else error message 2

2023-02-03 20:07 UTC, norkans7 commented on temba/channels/types/whatsapp/views.py
> +        org = self.request.org
I see I can move that to the form clean method

2023-02-06 16:55 UTC, rowanseymour requested changes

2023-02-06 16:55 UTC, rowanseymour commented on temba/channels/types/whatsapp/views.py
> +                        _("That number is already connected (%s)") % self.cleaned_data["number"]
https://docs.djangoproject.com/en/4.1/ref/forms/validation/#raising-validationerror

2023-02-06 16:55 UTC, rowanseymour commented on temba/channels/types/whatsapp/views.py
> +                    _("That number is already connected to another account - %(org)s (%(user)s)")
Should be we exposing information about another workspace? I appreciate it's useful but maybe better to limit unless user is on the other org.

cc @ericnewcomer

2023-02-06 16:58 UTC, norkans7 commented on temba/channels/types/whatsapp/views.py
> +                    _("That number is already connected to another account - %(org)s (%(user)s)")
Actually I had thought we probably need to use the channel link for this and fi the user can access that then they see the channel from the link.

2023-02-06 17:03 UTC, rowanseymour commented on temba/channels/types/whatsapp/views.py
> +                    _("That number is already connected to another account - %(org)s (%(user)s)")
does the new org servicing stuff work for non-staff users? i.e. can they use it switch orgs?

2023-02-06 18:25 UTC, ericnewcomer commented on temba/channels/types/whatsapp/views.py
> +                    _("That number is already connected to another account - %(org)s (%(user)s)")
We should say it's in use, but not by whom.

2023-02-06 18:29 UTC, rowanseymour commented on temba/channels/types/whatsapp/views.py
> +                    _("That number is already connected to another account - %(org)s (%(user)s)")
How about...

`Number is already connected to this workspace`

`Number is already connected to another workspace`

2023-02-06 18:48 UTC, norkans7 commented on temba/channels/views.py
> +            if existing.org == self.request.org:
@rowanseymour I remembered why we had used the approach of calling form invalid in form valid is because these forms are hidden on the UI as we submit them by button on numbers for Twilio, Vonage ...

2023-02-06 20:28 UTC, rowanseymour approved these changes

2023-02-06 20:28 UTC, merged