Outgoing message status changes
nyaruka/rapidpro pull request #4337
Opened 2023-02-21 18:02 UTC by rowanseymour

* Re-add `Msg.STATUS_INITIALIZING` to use for outgoing messages which fail to queue 
* Include `Msg.STATUS_ERRORED` messages in Outbox view and API folder

2023-02-21 18:06 UTC, rowanseymour commented on temba/sql/current_functions.sql
> +      IF _msg.status = 'I' OR _msg.status = 'Q' OR _msg.status = 'E' THEN
changing this _whilst_ orgs have messages in an ERRORED state but not considered part of their outbox may lead to some orgs ending up with negative counts on their Outbox views. Only a problem for us since we're live deploying, can fix with a data migration or a bit of 🤠

2023-02-21 21:00 UTC, rowanseymour commented on temba/msgs/migrations/0221_remove_msg_msgs_outgoing_to_retry_and_more.py
> +    IF _msg.VISIBILITY = 'V' THEN
note that we don't allow deletion of outgoing messages and we don't have any messages like this in prod... but I talked myself out of removing this in case we want to support deleting outgoing messages in future

2023-02-22 14:48 UTC, norkans7 requested changes
Android syncing needs to match these as well for MT messages

2023-02-22 14:57 UTC, rowanseymour commented
@norkans7 don't think that's an issue - mailroom creates android messages with `status=Q`, then `Msg.update` is called in relayer syncing and can update them as `status=E|F|S|D`

2023-02-22 16:53 UTC, rowanseymour commented
The Android relayer handles retries - it's not part of the usual message retry task in mailroom

2023-02-22 17:05 UTC, norkans7 commented
I mean those resent from the failed folder, and I just noticed that mailroom as well was not handling that correctly I think

2023-02-22 17:12 UTC, rowanseymour commented
Ah those go back into status=Q and are requeued to courier or resynced over Android... the latter might be broken but that doesn't relate to this PR

2023-02-22 17:18 UTC, norkans7 commented
I think those are currently to `P` https://github.com/nyaruka/mailroom/pull/41/files#diff-96ebd6741cc8a5d068db3fd9ae411d261c2fd36517c2da207fd8d44846f8ae5cR670-R680 

And probably android will need to pick `I` msgs in https://github.com/nyaruka/rapidpro/blob/9768bae4b48131d50fb64211254e4e6aa7cc4f55/temba/channels/android/__init__.py#L46

2023-02-22 17:58 UTC, rowanseymour commented
Ah good spot. Resending should update them to Q or F if they are unsendable.

Re the messages that we sync for Android... I think that's just Q. They're never going to be I, and if they're W.. they're already sent no?

2023-02-22 19:21 UTC, norkans7 approved these changes

2023-02-22 20:37 UTC, merged