new schedule message - add compose component
nyaruka/rapidpro pull request #4403
Opened 2023-03-10 10:05 UTC by susanm74

part of the fix for https://github.com/nyaruka/temba-components/issues/282

2023-03-17 16:41 UTC, susanm74 commented on temba/msgs/models.py
> +    MAX_ATTACHMENT_LEN = 10  # settings.MSG_ATTACHMENT_SIZE  # max attachments allowed in a broadcast
@ericnewcomer @rowanseymour @norkans7 thinking to add MSG_ATTACHMENT_SIZE =10 to settings_common.py just below the settings MSG_FIELD_SIZE = 640 (and perhaps update MSG_FIELD_SIZE to MSG_TEXT_SIZE?)

2023-03-17 16:42 UTC, susanm74 commented on temba/msgs/models.py
> +            # todo - is there a way to simplify this logic / do this better?
@ericnewcomer @rowanseymour @norkans7 hoping there's a more concise way of doing this, the below was how i've gotten things initially working for now, but i'm guessing there's a better way to do this (also i noticed that we don't really use literal_eval anywhere so i'm guessing that's not preferred)

2023-03-17 16:45 UTC, susanm74 commented on temba/utils/fields.py
> +        compose_item = json.loads(list_item)  # returns a string
@ericnewcomer @rowanseymour @norkans7 similar to my other comment, felt a bit weird to need to do json.loads twice to return value as a dict and not a string, the below is how i've gotten things initially working for now, but i'm guessing there's a better way to do this?

2023-03-17 17:25 UTC, susanm74 commented on temba/contacts/views.py
>                          name_field = forms.CharField(
@ericnewcomer unfortunately i haven't been able to crack the infinite loop yet, but you mentioned tracking down an example of a django form using a temba-textinput widget with an initial value - i did a pass through the code, and this was the one thing i found that looked like it might be helpful re: seeing how the initial param is being used, but i haven't 100% verified that this is a relevant example of setting an initial value just yet

2023-03-17 18:42 UTC, rowanseymour commented on temba/msgs/models.py
> +    MAX_ATTACHMENT_LEN = 10  # settings.MSG_ATTACHMENT_SIZE  # max attachments allowed in a broadcast
I think we just need `Msg.MAX_ATTACHMENTS = 10`

2023-03-17 18:43 UTC, rowanseymour commented on temba/settings_common.py
> +MSG_ATTACHMENT_SIZE = 10  # used for broadcast attachments, and message attachments
don't need this

2023-03-17 18:43 UTC, rowanseymour commented on temba/msgs/models.py
> +            # todo - is there a way to simplify this logic / do this better?
not following what this method is for... ?

2023-03-17 19:58 UTC, ericnewcomer commented on temba/msgs/models.py
> +            # todo - is there a way to simplify this logic / do this better?
I think for displaying attachments, we can have this logic in the template. Something similar to this.. https://github.com/nyaruka/rapidpro/blob/main/templates/msgs/message_box_spa.haml#L51

2023-03-17 20:08 UTC, rowanseymour commented on temba/msgs/models.py
> +            # todo - is there a way to simplify this logic / do this better?
Ah ok this is like `Broadcast.get_text` to determine how to render the broadcast content in 1) the list page, and 2) the contact read page up-coming tab..

In which case I'd modify `Broadcast.get_text` to be `Broadcast.get_content` returning a tuple of text, attachments, because you're going to want the same logic around picking a language.

I'm still lost as to what `ast.literal_eval` is for... you just need the attachments as strings in the `<content-type>:<url>` format... and they're already in that format in `translations`.

2023-03-18 01:28 UTC, susanm74 commented on temba/msgs/models.py
> +            # todo - is there a way to simplify this logic / do this better?
@ericnewcomer @rowanseymour ah cool, thanks guys, will update accordingly

2023-03-20 10:15 UTC, susanm74 commented on temba/utils/fields.py
> +        compose_item = json.loads(list_item)  # returns a string
ok so it looks like the `"` in the `list_item` string are double escaped i.e. `\\"`, and so the first json.loads() is what converts the `"` from being double escaped to single escaped i.e. `\\"` -> `\"`, and then the second json.loads() is what converts the `compose_item` string from a string to a dict - still feels a bit weird, but i guess necessary, and works, to ultimately return `value` as a dict

2023-03-20 15:18 UTC, susanm74 commented on temba/msgs/models.py
> +                attachment = json.loads(attachment.replace("'", "\""))
@ericnewcomer @rowanseymour @norkans7 
when i ran the code checks locally, this line went from this:
`attachment = json.loads(attachment.replace("'", "\""))`
to this
`attachment = json.loads(attachment.replace("'", """))`
and so i had to manually revert that one change before checking in my changes

the attachments string contains single-quotes, so there's a need to replace the single-quotes with double-quotes in order to convert the string to a python dict (to generate a list of formatted attachments using the <content_type>:<url> format), but i think this will cause issues if it keeps getting overwritten by the code checks - any ideas for an alternative that will play well with the code checks?

2023-03-20 15:24 UTC, susanm74 commented on temba/msgs/models.py
> +                attachment = json.loads(attachment.replace("'", "\""))
@ericnewcomer @rowanseymour @norkans7 whoops never mind, looks like a typo must've somehow snuck in there, and it's replacing it with this line, which is fine:
`attachment = json.loads(attachment.replace("'", '"'))`

2023-03-20 16:17 UTC, rowanseymour requested changes

2023-03-20 16:17 UTC, rowanseymour commented on temba/msgs/models.py
> +        return content
I think you want one method here which you can call from a template, and I don't think it needs to be much more complicated than the current logic in `get_text`, because the data is already in the format that you want it. Something like...

```python
def get_translation(self, contact=None) -> dict:
    """
    Gets a translation to use to display this broadcast. If contact is provided and their language is a valid flow
    language and there's a translation for it then that will be used.
    """

    def trans(d):
        return {"text": "", "attachments": []} | d  # ensure we always have text+attachments

        if contact and contact.language and contact.language in self.org.flow_languages:  # try contact language
            if contact.language in self.translations:
                return trans(self.translations[contact.language])

        if self.org.flow_languages[0] in self.translations:  # try org primary language
            return trans(self.translations[self.org.flow_languages[0]])

    return trans(self.translations[self.base_language])  # should always be a base language translation
```

If you're seeing encoding issues then maybe there's a problem with how the data is being passed _from_ the component.

2023-03-21 14:36 UTC, rowanseymour commented on temba/msgs/models.py
> +    MAX_ATTACHMENTS = 10  # max attachments allowed in a broadcast
seems like both of these constants can just live on `Msg` - they're never going to be different for broadcasts

2023-03-22 02:33 UTC, ericnewcomer commented on temba/msgs/models.py
> +        return content
This example is super confusing to me.  I'm assuming `self.translations` is something like..

```python
{ 
  'eng': { 'text': 'arst...', 'attachments': [...]},
  'esp': { 'text': 'zxcv...', 'attachments': [...]}
}
```

Why is your inner method example recursive? Seems this should just be figuring out the right language and then just indexing into the dict for it with a backdown if it's not there. What am I missing?

2023-03-22 02:36 UTC, ericnewcomer commented on temba/msgs/models.py
> +        return content
Lol, I think your indentation is off. Bah, python!

2023-03-22 02:40 UTC, rowanseymour commented on temba/msgs/models.py
> +        return content
argh yup lemme fix.. It's just `Broadcast.get_text` but instead of returning `["text"]`, return the whole translation - but then calling a little utility to ensure every translation has "text" and "attachments"

2023-03-22 02:44 UTC, susanm74 commented on temba/msgs/models.py
> +        return content
@ericnewcomer @rowanseymour ah, thanks both, ok will replace get_text, get_attachments, and get_content with get_translations, and then do the final concatenation of `{attach.content_type}:{attach.url}` directly in the template

2023-03-22 02:47 UTC, rowanseymour commented on temba/msgs/models.py
> +        return content
I don't think you need to mess with the attachments - they're already in the `<content-type>:<url>` format, and you just pass that to the `attachment_button` template tag

2023-03-22 02:53 UTC, susanm74 commented on temba/msgs/models.py
> +        return content
@rowanseymour ah ok cool, i'm seeing this now in the templatetags registered on the attachment.haml

2023-03-22 05:12 UTC, susanm74 commented on temba/msgs/models.py
> +    MAX_ATTACHMENTS = 10  # max attachments allowed in a broadcast
@rowanseymour cool, will do... what about `Broadcast.MAX_TEXT_LEN`? it's also currently the same as the `Msg` one - could do the same for that as well

2023-03-23 08:57 UTC, susanm74 commented on temba/msgs/models.py
> +        return content
@rowanseymour @ericnewcomer i think i've gotten these encoding kinks ironed out across the RP widget and the TC component, but just want to sanity check a few details on the broadcast backend side...

- when initially creating a broadcast, is the goal to save only a list of "content_type:url" within the broadcast translations json blob? (similar to what we do when creating a msg?)
- for list/read page display purposes, only having a list of "content_type:url" will work just fine...
- but when editing a broadcast, loading the edit formax (which contains the compose component) requires knowing a bit more info about each individual attachment (filename, file type, file size, etc) so that the the attachments list displays properly within the component... i'm assuming this means i'll just need to go and grab those attachments from the media table (based on their url) when loading the broadcast edit formax... but can you let me know if that all sounds about right?

2023-03-23 22:39 UTC, rowanseymour commented on temba/msgs/models.py
> +        return content
Hmm I hadn't thought of that but yeah... you'll need to do something like how `temba.api.v2.fields.MediaField` works and take the `<content-type>:<url>`, parse out the UUID and lookup the media object.

2023-03-27 10:29 UTC, susanm74 commented on templates/msgs/broadcast_scheduled_spa.haml
> +              -for attachment in object.get_attachments
@ericnewcomer @rowanseymour @norkans7 is there a way to pass the `translation` param into the `object.get_text` and `object.get_attachments` functions without making these into custom template tags? i keep getting a pesky parsing error when i try to do this, but prob worthwhile to prevent `get_translation` from being called twice on every broadcast...

2023-03-27 12:04 UTC, norkans7 commented on templates/msgs/broadcast_scheduled_spa.haml
> +              -for attachment in object.get_attachments
probably change the for loop to `-for attachment in translation.attachments` instead of the model method since you have `-with object.get_translation as translation` above

2023-03-27 15:51 UTC, rowanseymour commented on templates/msgs/broadcast_scheduled.haml
> +              {{ translation }}
`translation.text`

2023-03-27 15:59 UTC, susanm74 commented on templates/msgs/broadcast_scheduled_spa.haml
> +              -for attachment in object.get_attachments
@norkans7 @rowanseymour ok so i'm trying to get translation.text and translation.attachments working, and while i'm no longer getting the parsing error, nothing is displaying when i add these as extra td's, and when i do an inspect, i see the td's in the html, but they're empty (whereas object.get_translation and object.get_text and object.get_attachments are populated with content as expected)... could it be something wrong with my "with" statement?

i tried this:
- `-with object.get_translation as translation`
and this:
- `-with translation=object.get_translation`

but yeah, if i can get these display kinks worked out, then we can def get rid of get_text() and get_attachments()

2023-03-27 16:02 UTC, susanm74 commented on templates/msgs/broadcast_scheduled_spa.haml
> +              -for attachment in object.get_attachments
here's what i see when i add a few extra td's to the broadcast list page template
<img width="1600" alt="Screen Shot 2023-03-27 at 10 56 19 PM" src="https://user-images.githubusercontent.com/854012/227997930-ca2a599e-e2ae-414c-88e0-28e00181b2d7.png">

2023-03-27 16:04 UTC, susanm74 commented on templates/msgs/broadcast_scheduled_spa.haml
> +              -for attachment in object.get_attachments
and then here's the relevant code in the broadcast_scheduled_spa.haml (also the same in broadcast_scheduled.haml)
<img width="1182" alt="Screen Shot 2023-03-27 at 11 03 21 PM" src="https://user-images.githubusercontent.com/854012/227998371-8678f29c-d50c-4d88-8bf4-1ca9566df66c.png">

2023-03-27 16:06 UTC, rowanseymour commented on templates/msgs/broadcast_scheduled.haml
> +              {{ translation }}
yeah

2023-03-27 16:07 UTC, rowanseymour commented on templates/msgs/broadcast_scheduled_spa.haml
> +              -for attachment in object.get_attachments
Re `with`, both syntaxes should work but `=` is preferred https://docs.djangoproject.com/en/4.1/ref/templates/builtins/#with

I think the problem is that the places you're referencing `translation` aren't properly nested within the `with`

2023-03-27 16:08 UTC, norkans7 commented on templates/msgs/broadcast_scheduled_spa.haml
> +              -for attachment in object.get_attachments
I think the `td` should be nested within the `-with`

2023-03-27 16:13 UTC, susanm74 commented on templates/msgs/broadcast_scheduled_spa.haml
> +              -for attachment in object.get_attachments
oh man, what a difference a single tab makes - thank you!

2023-03-27 17:31 UTC, susanm74 commented
@ericnewcomer @rowanseymour @norkans7 ok got the display issue fixed, and got rid of Broadcast.get_text and Broadcast.get_attachments in favor of get_translation everywhere...

- sanity check - does the BroadcastCRUDL -> Send class need to be updated/shipped with the rest of the updates in this PR or is that something we can update later as a separate PR?

- otherwise, currently cracking on with unit tests and hoping to wrap up on those in the next day or so

2023-03-29 17:37 UTC, susanm74 commented
@ericnewcomer @rowanseymour @norkans7 ok this is RFR, so have at it...

the only thing that i'm a bit stumped on is that codecov is saying that lines that temba/msgs/views.py#L299 and temba/msgs/views.py#L301 aren't covered by tests, but i've got the following 3 unit tests to cover the broadcast update validation scenarios:
- test_scheduled_update_missing_media
- test_scheduled_update_text_max_length
- test_scheduled_update_attachments_max_files
any ideas here?

2023-03-30 11:57 UTC, norkans7 commented
@susanm74 I think errors are raised from https://github.com/nyaruka/rapidpro/pull/4403/files#diff-1a628f054f2be55208982bcc902e0910d8ea792a8a801a48b16ba1ea2ea71059R211 so those lines are never reached.

I guess the solution is to remove the validations in `is_valid` and only use those in the `clean_*` methods

2023-03-30 12:06 UTC, norkans7 commented on temba/msgs/views.py
> +            # omnibox validations
I think we can move this omnibox validation into its own clean method and remove this `is_valid` here entirely

2023-03-31 08:50 UTC, susanm74 commented on temba/msgs/views.py
> +                        menu_id="flows",
@ericnewcomer can you sanity check that i added these correctly?... i know we discussed making the menu_id the same as the menu name vs. singular vs. plural... or should i leave these updates off and do them and the menu name updates to get rid of the wrapping _(...) as a follow-up PR?

2023-03-31 20:30 UTC, rowanseymour requested changes

2023-03-31 20:30 UTC, rowanseymour commented on templates/msgs/broadcast_scheduled_read_spa.haml
> +                    {% attachment_button attachment %}
as above

2023-03-31 20:30 UTC, rowanseymour commented on templates/msgs/broadcast_scheduled_spa.haml
> +                  {% attachment_button attachment %}
as above

2023-04-03 08:41 UTC, susanm74 commented on temba/msgs/attachments/compose.py
@rowanseymour when i tried moving the contents of compose.py into temba/utils.fields.py i got the following error:

- ImportError: cannot import name 'DependencyMixin' from partially initialized module 'temba.orgs.models' (most likely due to a circular import) (/home/runner/work/rapidpro/rapidpro/temba/orgs/models.py)

so i moved compose.py into the temba/utils dir and kept it in it's own file for now, but if we really want those fns to live inside of temba/utils/fields.py, i might need some help with resolving that error

2023-04-03 14:32 UTC, rowanseymour commented on temba/msgs/attachments/compose.py
it's fine there for now

2023-04-04 07:37 UTC, susanm74 commented on temba/msgs/views.py
> +            # omnibox validations
@ericnewcomer @rowanseymour @norkans7 still not sure how to go about resolving this - would it be a case where adding `pragma: needs cover` or `pragma: no cover` to these 2 lines would be appropriate?
- https://app.codecov.io/gh/nyaruka/rapidpro/pull/4403/blob/temba/msgs/views.py#L247
- https://app.codecov.io/gh/nyaruka/rapidpro/pull/4403/blob/temba/msgs/views.py#L249

2023-04-04 07:40 UTC, susanm74 commented on temba/msgs/views.py
> +                        menu_id="flows",
@ericnewcomer just wanted to confirm these updates should be included in the PR and implemented as expected

2023-04-04 10:08 UTC, norkans7 commented on temba/msgs/models.py
> +        def trans(d):
`trans` here seems confusing to me as a name

2023-04-04 10:18 UTC, norkans7 commented on temba/msgs/views.py
> +            # omnibox validations
I still think that validation should be used instead of the one in `is_valid`

Have you tried to remove the `is_valid` completely and move the omnibox validation in its only clean method?

2023-04-04 14:23 UTC, rowanseymour commented on temba/msgs/models.py
> +        def trans(d):
it's returning a `translation` object and it's scoped inside a function so not used far from its declaration.. seems fine to me

2023-04-04 22:12 UTC, rowanseymour commented on temba/utils/fields.py
> +        return value
it's ok to be a bit more succint... `return json.loads(data[name])`

2023-04-04 23:22 UTC, rowanseymour commented on temba/msgs/views.py
> +                valid = super().is_valid()
I see this approach of using `is_valid` came from the original form and I'm struggling to remember why it is that way, but if it works.. cool

We can merge things like this tand then go back and see if we can clean things up so that putting `required=True` is enough to have *it* generate errors.

2023-04-05 10:37 UTC, norkans7 approved these changes

2023-04-05 17:40 UTC, merged