More vonage connect view to the channel type
nyaruka/rapidpro pull request #4541
Opened 2023-05-05 15:54 UTC by norkans7

2023-05-09 14:53 UTC, rowanseymour requested changes

2023-05-09 14:53 UTC, rowanseymour commented on temba/channels/models.py
> +    SESSION_VONAGE_API_SECRET = "VONAGE_API_SECRET"
why do these need to be in `Channel` ?

2023-05-09 14:53 UTC, rowanseymour commented on temba/channels/types/vonage/tests.py
> +        self.assertFalse(Channel.SESSION_VONAGE_API_KEY in self.client.session)
`self.assertNotIn`

2023-05-09 14:53 UTC, rowanseymour commented on temba/channels/types/vonage/tests.py
> +        self.assertTrue(Channel.SESSION_VONAGE_API_KEY in self.client.session)
`self.assertIn`

2023-05-09 14:53 UTC, rowanseymour commented on templates/channels/types/vonage/claim.haml
> +- block account-trial-warning
`-block`

feels a bit weird this is using `account-trial-warning`,  no?

2023-05-09 14:57 UTC, norkans7 commented on templates/channels/types/vonage/claim.haml
> +- block account-trial-warning
I will rename that

2023-05-09 15:36 UTC, norkans7 commented on temba/channels/types/vonage/tests.py
> +        self.assertFalse(Channel.SESSION_VONAGE_API_KEY in self.client.session)
updated

2023-05-10 19:20 UTC, rowanseymour commented on temba/channels/types/vonage/tests.py
> +            config={Channel.CONFIG_VONAGE_API_KEY: "1234", Channel.CONFIG_VONAGE_API_SECRET: "secret"},
can't these move into the channel package too?

2023-05-11 14:21 UTC, norkans7 commented on temba/channels/types/vonage/tests.py
> +            config={Channel.CONFIG_VONAGE_API_KEY: "1234", Channel.CONFIG_VONAGE_API_SECRET: "secret"},
Updated, some channels tests import those locally to avoid circular dependency issue

2023-05-11 15:58 UTC, merged