Rename Twiml API channel to Somleng
nyaruka/rapidpro pull request #4546
Opened 2023-05-06 07:52 UTC by dwilkie

2023-05-09 10:41 UTC, norkans7 commented on temba/settings_common.py
> +    "temba.channels.types.somleng.SomlengType",
we use alphabetical order here, so move that above

2023-05-11 03:03 UTC, dwilkie commented
> poetry run ./code_check.py

I tried running this locally but got an error ```ModuleNotFoundError: No module named 'temba.settings'```

2023-05-11 03:15 UTC, dwilkie commented
> @dwilkie you need to run `poetry run ./code_check.py` to run black, isort and ruff for code formatting checks

I got it working now and committed the changes

2023-05-11 12:29 UTC, norkans7 commented
@dwilkie tests need an update

2023-05-11 12:48 UTC, dwilkie commented
> @dwilkie tests need an update

I'm not sure how to fix this test. I don't understand what it's doing.

2023-05-11 13:06 UTC, dwilkie commented
> https://github.com/nyaruka/rapidpro/blob/4e12d0e2ab19515387d7f9d87e74e64e5fa20c3d/temba/channels/types/somleng/tests.py#L22
> 
> The test is checking the channel type is listed on the claim page, I think You renamed `TwiML` to `Somleng` then we can assert Somleng word is in the response so the type is listed on the channel claim page

https://github.com/nyaruka/rapidpro/pull/4546/commits/3bf53ed15d65738f0f0eeac1438e0693ac5b14b0

2023-05-11 14:18 UTC, norkans7 approved these changes
Looks good

2023-05-11 15:59 UTC, rowanseymour requested changes

2023-05-11 15:59 UTC, rowanseymour commented on templates/channels/types/twiml_api/claim.haml
this path needs updated

2023-05-11 19:21 UTC, rowanseymour commented
Gonna merge and fix...

2023-05-11 19:21 UTC, merged