Org import async
nyaruka/rapidpro pull request #4650
Opened 2023-06-09 14:55 UTC by norkans7

2023-06-12 16:58 UTC, rowanseymour requested changes

2023-06-12 17:04 UTC, rowanseymour commented on temba/orgs/views.py
> +    class ImportProgress(SpaMixin, OrgPermsMixin, SmartTemplateView):
Yeah makes sense

2023-06-12 20:20 UTC, rowanseymour requested changes

2023-06-12 20:20 UTC, rowanseymour commented on temba/orgs/models.py
> +class OrgImport(TembaUUIDMixin, SmartModel):
don't think we really need uuids here and the views don't need to use uuids in the URLs either - this is not a thing the engine or API needs to know about

2023-06-12 20:20 UTC, rowanseymour commented on temba/orgs/models.py
> +    started_on = models.DateTimeField(null=True)
I think just use `created_on`

2023-06-12 20:20 UTC, rowanseymour commented on temba/orgs/models.py
> +    finished_on = models.DateTimeField(null=True)
can also just use `modified_on`

2023-06-19 16:44 UTC, rowanseymour requested changes

2023-06-19 16:44 UTC, rowanseymour commented on temba/orgs/models.py
> +    return f"org_imports/{instance.org_id}/{uuid4()}{ext}"
to match exports and keep all of an orgs data in one place, I think we want...

`f"{settings.STORAGE_ROOT_DIR}/{instance.org_id}/org_imports"`

Does seem contact imports are different but we should fix that.

2023-06-19 16:44 UTC, rowanseymour commented on templates/orgs/orgimport_read.haml
> +            -trans "An error happened during import , please try again."
no space before comma

2023-06-19 16:44 UTC, rowanseymour commented on templates/orgs/orgimport_read.haml
> +              %a(href="{% url 'flows.flow_list' %}")
This is bit silly but maybe it will do until we have a log of some sort of what the import task did

2023-06-19 16:44 UTC, rowanseymour commented on templates/orgs/orgimport_read.haml
> +            -trans "Import starting soon"
"About to start..."

2023-06-19 16:44 UTC, rowanseymour commented on templates/orgs/orgimport_read.haml
> +            -trans "Import in progress ..."
"In progress..."

2023-06-19 16:44 UTC, rowanseymour commented on templates/orgs/orgimport_read.haml
> +            -trans "An error happened during import , please try again."
"An error happened, please try again."

2023-06-19 16:44 UTC, rowanseymour commented on templates/orgs/orgimport_read.haml
> +            -trans "Import finished successfully"
"Finished successfully"

2023-06-19 16:44 UTC, rowanseymour commented on temba/orgs/views.py
> +        class FlowImportForm(forms.ModelForm):
`class Form`

2023-06-19 17:17 UTC, norkans7 commented on temba/orgs/models.py
> +    return f"org_imports/{instance.org_id}/{uuid4()}{ext}"
I think what we have is actually similar

https://github.com/nyaruka/rapidpro/blob/0a1125585208d0f2c078c1e41082b783feeedc6e/temba/contacts/models.py#L2029

2023-06-19 17:17 UTC, norkans7 commented on temba/orgs/models.py
> +    return f"org_imports/{instance.org_id}/{uuid4()}{ext}"
https://github.com/nyaruka/rapidpro/blob/0a1125585208d0f2c078c1e41082b783feeedc6e/temba/contacts/models.py#L2031

2023-06-20 11:42 UTC, rowanseymour commented on templates/orgs/orgimport_read.haml
> +        }, 3000);
just noticed.. this isn't using `derive_refresh`.. so maybe just get rid of it?

2023-06-20 16:11 UTC, rowanseymour requested changes

2023-06-20 16:11 UTC, rowanseymour commented on templates/orgs/orgimport_create.haml
> +      var file = $("#file").val();
I thought jquery was gone? I'm surprised this still works for contact imports. I think this should be `querySelector("#file").value`... @ericnewcomer ?

2023-06-20 16:49 UTC, rowanseymour commented on templates/orgs/orgimport_create.haml
> +      var file = $("#file").val();
Well I'm assuming this works so we can merge and then go clean up jquery on both import pages

2023-06-20 16:50 UTC, merged