Add send broadcast and start flow bulk actions to contact group page
nyaruka/rapidpro pull request #4935
Opened 2023-10-30 14:25 UTC by norkans7

2023-10-30 19:27 UTC, rowanseymour requested changes

2023-10-30 19:27 UTC, rowanseymour commented on temba/contacts/views.py
> +                bulk_actions += ("send", "start-flow")
shouldn't this be `flows.flow_start` and `msgs.broadcast_create` ?

2023-10-30 20:53 UTC, norkans7 commented on temba/contacts/views.py
> +                bulk_actions += ("send", "start-flow")
I have seen those used in https://github.com/nyaruka/rapidpro/blob/e23a6514791f2b61ef16fe89a601cc5e36987bea/templates/includes/short_pagination.html#L63

And I used `contacts.contact_update` to be consistent with what is used on the `List` view https://github.com/nyaruka/rapidpro/blob/e23a6514791f2b61ef16fe89a601cc5e36987bea/temba/contacts/views.py#L874

2023-10-31 09:40 UTC, norkans7 commented on temba/contacts/views.py
> +                bulk_actions += ("send", "start-flow")
Adjust that in both places

2023-10-31 13:25 UTC, rowanseymour commented on temba/contacts/views.py
> +            actions = ("block", "archive") if self.group.is_smart else ("block", "unlabel")
these also need gated by `contacts.contact_update`

The current `get_bulk_actions` way of working isn't ideal but let's get this fixed this way for now and then we can try to clean it up later.

2023-10-31 14:15 UTC, merged