Add view to verify email
nyaruka/rapidpro pull request #4941
Opened 2023-11-01 09:23 UTC by norkans7

2023-11-01 09:24 UTC, norkans7 commented on templates/orgs/user_verify_email.html
> +                {% blocktrans trimmed %}
![Uploading Monosnap Email verification 2023-11-01 11-20-27.png…]()

2023-11-01 09:25 UTC, norkans7 commented on temba/orgs/views.py
> +    class VerifyEmail(SpaMixin, SmartReadView):
I used `SmartReadView` to rely on redirect instead of requiring the uses to click a button on the form to submit.

2023-11-01 14:09 UTC, rowanseymour requested changes

2023-11-01 14:09 UTC, rowanseymour commented on temba/orgs/views.py
> +        def pre_process(self, request, *args, **kwargs):
I think a better flow here is that we don't redirect immediately

Mark the user as verified or not, and then display a no-nav page that says "Thank you, your email address has been verified..", and then after 3 seconds uses JS to redirect to the start page.

2023-11-01 14:09 UTC, rowanseymour commented on temba/orgs/views.py
> +            if request.user.settings.email_verification_secret == self.kwargs["secret"]:
Might want an index on `email_verification_secret`

2023-11-01 14:09 UTC, rowanseymour commented on templates/orgs/user_verify_email.html
> +                {% blocktrans trimmed %}
Btw I'm not able to view these monosnap uploads... they show as broken links for me

2023-11-01 14:12 UTC, norkans7 commented on templates/orgs/user_verify_email.html
> +                {% blocktrans trimmed %}
uploaded them again

2023-11-01 14:14 UTC, norkans7 commented on temba/orgs/views.py
> +            if request.user.settings.email_verification_secret == self.kwargs["secret"]:
settings is cache properly https://github.com/nyaruka/rapidpro/blob/06f3e432d2a9bba9ec634ae1050979fbcb657c35/temba/orgs/models.py#L272

I think we do not need an index since since we use user field in the function

2023-11-01 14:19 UTC, rowanseymour commented on temba/orgs/views.py
> +            if request.user.settings.email_verification_secret == self.kwargs["secret"]:
Sorry i meant for the line above that looks to see if there is a verification token that exists with that secret.

Maybe cleaner to do:

1. Lookup user by verification secret
2. If `None` show no-nav page with error message, then redirect to login
3. If `!= request.user`, show no-nav page with error message, then redirect to login, with redirect back to verify page
4. If `== request.user`, verify user, show no-nav page with success message, then redirect to start page.

2023-11-01 14:22 UTC, rowanseymour commented on templates/orgs/user_verify_email.html
> +                {% blocktrans trimmed %}
I notice in the screenshots in the PR description, the success message is shown twice... but see other comment.. I don't think we actually need those messages

2023-11-01 14:23 UTC, norkans7 commented on temba/orgs/views.py
> +            if request.user.settings.email_verification_secret == self.kwargs["secret"]:
right, I see we need the index for that query

2023-11-01 19:18 UTC, norkans7 commented on templates/frame.html
> -            {% if messages %}
This removes the duplicate display of messages

2023-11-01 19:20 UTC, norkans7 commented on temba/orgs/views.py
> +            return super().pre_process(request, *args, **kwargs)
Still need the pre_process so we can update the verification status.
I used parameter `verify=1` but still make sure the user matches

2023-11-01 19:32 UTC, norkans7 commented
<img width="1196" alt="Monosnap Email verification 2023-11-01 21-30-55" src="https://github.com/nyaruka/rapidpro/assets/1040571/a244dada-e70c-4c62-8846-c8ecc2a05a11">
<img width="1398" alt="Monosnap Email verification 2023-11-01 21-30-28" src="https://github.com/nyaruka/rapidpro/assets/1040571/8feac982-fb25-46b2-88c2-98fddf9af17a">
<img width="1317" alt="Monosnap Email verification 2023-11-01 21-30-03" src="https://github.com/nyaruka/rapidpro/assets/1040571/567954d3-f682-432f-aae9-93ff52b4615d">


And redirects after 3 seconds

2023-11-01 19:46 UTC, ericnewcomer commented
These views should have a menu_path set. Probably to settings?

2023-11-01 20:05 UTC, norkans7 commented
<img width="1089" alt="Monosnap Email verification 2023-11-01 22-03-34" src="https://github.com/nyaruka/rapidpro/assets/1040571/8c4dfedc-1f5c-41d5-9765-26946ff28800">
<img width="1261" alt="Monosnap Email verification 2023-11-01 22-03-01" src="https://github.com/nyaruka/rapidpro/assets/1040571/f74a3873-7c98-44f0-9fa2-ace800b2d2fe">
<img width="1157" alt="Monosnap Email verification 2023-11-01 21-58-55" src="https://github.com/nyaruka/rapidpro/assets/1040571/e05f302e-4af5-4f53-89b8-e426c6fd0079">

Added menu path to Account

2023-11-02 17:35 UTC, rowanseymour commented on temba/settings_common.py
> +    "orgs.user": ("token", "verify_email"),
I don't think it's worth defining new permissions for things we want all users to have access to and I recently removed the permissions around two factor auth for this reason - just use `user.is_authenticated` the view

2023-11-06 19:20 UTC, rowanseymour requested changes

2023-11-06 19:20 UTC, rowanseymour commented on temba/orgs/views.py
> +        def user_settings(self, **kwargs):
I think this view would be simpler if this was the user.. e.g. `user_by_secret`. The existence of `UserSettings` is kind of an implementation detail.

2023-11-06 19:20 UTC, rowanseymour commented on temba/orgs/views.py
> +            return super().pre_process(request, *args, **kwargs)
Not following why we need a parameter... ?

2023-11-06 21:13 UTC, norkans7 commented on temba/orgs/views.py
> +            return super().pre_process(request, *args, **kwargs)
We want to update the flag for email_status in the DB? so we do that with this same view

2023-11-06 21:25 UTC, norkans7 commented on temba/orgs/views.py
> +            return super().pre_process(request, *args, **kwargs)
without the parameter we are retrieving the secret is valid and check the user is the one logged in, then if all matches the JS side redirect to this view with that parameter so we update the email_status in the DB too.

2023-11-06 21:31 UTC, rowanseymour commented on temba/orgs/views.py
> +            return super().pre_process(request, *args, **kwargs)
I'm still not following...

1. user clicks link in email
2. pre_process redirects them to login page
3. login page redirects them back to verify page
4. if `self.request.user.settings.email_status != VERIFIED`, update to `VERIFIED`

2023-11-06 21:42 UTC, norkans7 commented on temba/orgs/views.py
> +            return super().pre_process(request, *args, **kwargs)
so we update the email _status in get_context method during the GET request.

2023-11-06 21:44 UTC, rowanseymour commented on temba/orgs/views.py
> +            return super().pre_process(request, *args, **kwargs)
no.. you can still update it in `pre_process` if there's no redirection (i.e. request user == email secret user)

2023-11-06 21:46 UTC, rowanseymour commented
> These views should have a menu_path set. Probably to settings?

@ericnewcomer I think it could be just a no-nav with a card of text that then redirects with JS to org_start after X seconds

2023-11-06 21:57 UTC, norkans7 commented on temba/orgs/views.py
> +            return super().pre_process(request, *args, **kwargs)
I'll check again on that

2023-11-07 08:36 UTC, norkans7 commented on temba/orgs/views.py
> +            return super().pre_process(request, *args, **kwargs)
The reason we need that parameter si to be able to show the verification was successful and then redirect
without that we just redirect to the account page, I guess that is fine too as in the next PR we'll have a label showing the email is verified

2023-11-07 20:36 UTC, rowanseymour commented
@norkans7 just chatted to @ericnewcomer about this - the verify view should just be a no-nav page with a card with some text, that redirects after 3 seconds.

2023-11-07 21:56 UTC, norkans7 commented
@rowanseymour I made the adjustment to use the no_nav template, please review again

<img width="1582" alt="Monosnap Adam McAdmin 2023-11-07 23-52-05" src="https://github.com/nyaruka/rapidpro/assets/1040571/32217880-c86f-479f-8d9a-4fbb5cfb7496">


<img width="1534" alt="Monosnap Adam McAdmin 2023-11-07 23-55-28" src="https://github.com/nyaruka/rapidpro/assets/1040571/9bdec725-1859-4210-b30e-b8e786fd1171">



<img width="1629" alt="Monosnap Adam McAdmin 2023-11-07 23-52-38" src="https://github.com/nyaruka/rapidpro/assets/1040571/952ed3c5-2b15-4cab-b42a-9e5304fc3c71">

2023-11-09 15:15 UTC, rowanseymour commented
Was trying to improve on the look of this view and ended up replacing the redirect with a button where needed...

<img width="615" alt="Captura de pantalla 2023-11-09 a la(s) 09 53 48" src="https://github.com/nyaruka/rapidpro/assets/675558/54d27620-7c3f-4ac2-b7f4-1f7f392f32e3">
<img width="620" alt="Captura de pantalla 2023-11-09 a la(s) 09 54 31" src="https://github.com/nyaruka/rapidpro/assets/675558/4fd3f610-43a7-483c-813a-477f3438904e">
<img width="719" alt="Captura de pantalla 2023-11-09 a la(s) 10 01 49" src="https://github.com/nyaruka/rapidpro/assets/675558/4ac36038-86df-492f-9293-56ccf04ee6af">

2023-11-09 15:19 UTC, norkans7 commented
What about having a min height on the card so it keep looking similar? the second screenshots looks different IMO

2023-11-09 15:38 UTC, rowanseymour commented
@norkans7 the second screenshot is of an error case that really shouldn't happen so I'm not too worried what it looks like

2023-11-09 15:40 UTC, norkans7 commented
Ahh okay

2023-11-09 15:41 UTC, merged