Add support for user to start the email verification
nyaruka/rapidpro pull request #4946
Opened 2023-11-02 12:14 UTC by norkans7

contains #4941 

Verify Email button on the account page in the edit user formax summary
<img width="1726" alt="Monosnap Account 2023-11-02 14-08-19" src="https://github.com/nyaruka/rapidpro/assets/1040571/17f1ae9b-e95b-48cb-b838-75912efc0908">

View for the user to trigger the email
<img width="1221" alt="Monosnap Email verification 2023-11-02 14-08-31" src="https://github.com/nyaruka/rapidpro/assets/1040571/2dd2e13b-2f46-4766-be34-e9ba08fd4b64">

Redirect to the account page
<img width="1728" alt="Monosnap Email verification 2023-11-02 14-09-00" src="https://github.com/nyaruka/rapidpro/assets/1040571/3d7ed65c-6f91-41d2-b0e4-3ce78c4ee47c">

Once the link is clicked the changes in #4941 will be taking care of validating the email

2023-11-07 10:47 UTC, norkans7 commented
<img width="924" alt="Monosnap Account 2023-11-07 12-47-22" src="https://github.com/nyaruka/rapidpro/assets/1040571/94a26f6a-5ba4-4eb9-b772-8b54020a0c16">

2023-11-09 16:00 UTC, rowanseymour commented
1. I'm not sure we need a verified button beside verified email addresses - because we want to get to a point where verified is the norm
2. The user shouldn't need to click to the "Send Verification Email" view and then click again to send the actual email.. just have the first button send the email

2023-11-10 12:10 UTC, norkans7 commented
We have the button for unverified emails and we show verified label for those verified emails

<img width="1446" alt="Monosnap Account 2023-11-10 14-06-00" src="https://github.com/nyaruka/rapidpro/assets/1040571/a085845f-388b-4397-85ca-3bad2d18587f">

Should I remove the verified label below?
<img width="1207" alt="Monosnap Monosnap Account 2023-11-10 14-05-25 png 2023-11-10 14-08-21" src="https://github.com/nyaruka/rapidpro/assets/1040571/ecfeb4e7-5164-44b0-b253-459449e3e1a9">

2) I switched to use posterize and a post only view

2023-11-10 12:33 UTC, norkans7 commented on temba/orgs/views.py
> +        success_message = _("Verification email sent")
@rowanseymour you mentioned we should stop using the success message but in this case we use posterize and I am not sure what will be a better way for feedback to the user.

2023-11-10 15:29 UTC, rowanseymour commented on temba/orgs/views.py
> +        success_message = _("Verification email sent")
yeah in this case it's ok

2023-11-10 15:47 UTC, norkans7 commented on templates/orgs/user_edit.html
> +      {% endif %}
@rowanseymour 
should I remove this label?

<img width="1207" alt="Monosnap Monosnap Account 2023-11-10 14-05-25 png 2023-11-10 14-08-21" src="https://github.com/nyaruka/rapidpro/assets/1040571/daf1d8a8-4a1f-438a-9d9e-8555c3d8698b">

2023-11-10 15:53 UTC, rowanseymour commented on templates/orgs/user_edit.html
> +      {% endif %}
I think so... the goal here is to make verified the norm.. make it part of the signup process

2023-11-10 16:22 UTC, norkans7 commented on templates/orgs/user_edit.html
> +      {% endif %}
Done

2023-11-10 17:46 UTC, ericnewcomer commented
Why is the view to trigger the email a page and not a modal?

2023-11-10 17:57 UTC, norkans7 commented
Currently we just have a button that posterizes to send the email, so not a page
<img width="1446" alt="Monosnap Account 2023-11-10 14-06-00" src="https://github.com/nyaruka/rapidpro/assets/1040571/2d8f86aa-735a-42d6-b669-2f627f8ef0e3">

Click on the button and the email is sent.

I can remove the old screenshots if they now confusing

2023-11-10 17:58 UTC, ericnewcomer commented
Ah, sorry for the confusion! Makes sense.

2023-11-29 22:10 UTC, rowanseymour commented on templates/orgs/user_send_verification_email.html
> +{% extends "smartmin/update.html" %}
is this template used?

2023-11-29 22:11 UTC, rowanseymour commented on temba/orgs/models.py
> +            return
this only applies to the superuser if it exists so don't need to check this

2023-11-29 22:11 UTC, rowanseymour commented on temba/orgs/models.py
> +        to_email = self.email
doesn't need to be a variable

2023-11-29 22:11 UTC, rowanseymour commented on temba/orgs/tasks.py
> +    user = User.objects.get(pk=user_id)
id=

2023-11-30 14:36 UTC, rowanseymour requested changes

2023-11-30 14:36 UTC, rowanseymour commented on temba/orgs/models.py
> +        send_template_email(self.email, subject, template, context, org.branding)
Sometimes it makes sense to have this pattern of model method invoking task, task calling model method, but here it just feels like we're adding unhelpful complexity. We have...

```
User.send_verification
User.send_verification_email
send_user_verification_email_task
```

Let's just have a task called `send_user_verification_email` which is called by the view.

2023-11-30 14:36 UTC, rowanseymour commented on templates/orgs/user_edit.html
> +      {% blocktrans with email=user.username %}
trimmed

2023-11-30 18:15 UTC, merged