Add incident for WhatsApp templates not syncing
nyaruka/rapidpro pull request #5073
Opened 2024-03-01 11:49 UTC by norkans7

2024-03-02 16:00 UTC, rowanseymour requested changes

2024-03-04 14:07 UTC, rowanseymour commented on temba/utils/whatsapp/tasks.py
> +                    incident.end()
shouldn't there only every be one of these ? I think we have a constraint on scope... so we can just do `.first()` and if one exists.. end it.

2024-03-04 14:11 UTC, norkans7 commented on temba/utils/whatsapp/tasks.py
> +                    incident.end()
Yes, only one incident for a channel should be not ended

2024-03-04 14:17 UTC, rowanseymour approved these changes

2024-03-04 14:24 UTC, merged