Add type to template components
nyaruka/rapidpro pull request #5113
Opened 2024-03-18 23:00 UTC by rowanseymour

2024-03-18 23:02 UTC, rowanseymour commented on temba/utils/whatsapp/templates.py
> +            seen.add(match)
if params can be repeated (e.g. `Hello {{1}} {{1}}`) like in some of our tests then you can just count variable placeholders

2024-03-18 23:02 UTC, rowanseymour commented on temba/utils/whatsapp/templates.py
> +                params = [{"type": format.lower()}]
as I understand it none of these require parameters so are all safe to support

2024-03-18 23:03 UTC, rowanseymour commented on temba/utils/whatsapp/templates.py
> +        # TODO save components as a list... but for now organize them into a dict by type/index
the dict `"button.0": {}` way of organizing doesn't make so much sense any more... but keeping it as is for now

2024-03-19 07:01 UTC, norkans7 commented on temba/utils/whatsapp/templates.py
> +                params = [{"type": format.lower()}]
For now we mark them as not supported until we update the temba-components to support setting their values to send.

2024-03-19 07:04 UTC, norkans7 commented on temba/utils/whatsapp/templates.py
> +        comp_type = component["type"]
We need to make this case insensitive either lower or upper that, currently I guess we upper that.

2024-03-19 07:06 UTC, norkans7 requested changes
make image , video and location attachment not supported for now

2024-03-19 13:22 UTC, rowanseymour commented on temba/utils/whatsapp/templates.py
> +        comp_type = component["type"]
You've seen cases of this being lowercase?

2024-03-19 13:49 UTC, merged

2024-03-19 14:01 UTC, norkans7 commented on temba/utils/whatsapp/templates.py
> +        comp_type = component["type"]
I cannot remember that, but I think it is best to be case insensitive for that