Fix to limit sending user verification email
nyaruka/rapidpro pull request #5177
Opened 2024-04-15 14:06 UTC by norkans7

2024-04-15 14:07 UTC, norkans7 commented on code_check.py
> +    cmd("ruff check temba")
unrelated but that fix the ruff deprecation warning

2024-04-22 20:00 UTC, rowanseymour requested changes

2024-04-22 20:00 UTC, rowanseymour commented on temba/orgs/tasks.py
> +    r.hset(key, user.email, "1")
there's no reason for this to be a hash map.. can just be a regular set. But maybe better to keep it simpler since we're not expecting huge numbers of email verifications.

Can just be individual keys like: `email_verification_sent:rowan@foo.com` and give them an expiry of 10 minutes. If the key still exists next time, show the user a warning telling them to wait.

2024-04-23 15:39 UTC, rowanseymour approved these changes

2024-04-23 16:00 UTC, merged