Fix issues with twilio templates sync
nyaruka/rapidpro pull request #5230
Opened 2024-05-13 12:38 UTC by norkans7

2024-05-13 13:50 UTC, rowanseymour commented on temba/templates/types/twilio/type.py
> +        has_know_part = False
has_known_part ?

2024-05-13 14:10 UTC, norkans7 commented on temba/templates/types/twilio/type.py
> +        has_know_part = False
Ohh yes

2024-05-13 14:58 UTC, rowanseymour requested changes

2024-05-13 14:58 UTC, rowanseymour commented on temba/templates/types/twilio/type.py
> +            if "body" in raw[content_type] and raw[content_type].get("body") is not None:
Can't this just be `if raw[content_type].get("body"):`

2024-05-13 14:58 UTC, rowanseymour commented on temba/templates/types/twilio/type.py
> +        has_known_part = False
Maybe this variable needs a comment because I'm not understanding why we need a new variable in addition to `supported` and `components`... what does it mean?

2024-05-13 16:31 UTC, norkans7 commented on temba/templates/types/twilio/type.py
> +        has_known_part = False
I noticed types such as 
```
"twilio/card": {
                        "body": None,
                        "media": [],
                        "subtitle": "This message is from an unverified business.",
                        "actions": [],
                        "title": "Your ticket for *{{1}}*\n*Time* - {{2}}\n*Venue* - {{3}}\n*Seats* - {{4}}",
                    }
```
That we do not have a way to support and do not have any valid components we support

2024-05-13 17:55 UTC, rowanseymour requested changes

2024-05-13 17:55 UTC, rowanseymour commented on temba/templates/types/twilio/type.py
> +            if "body" in raw[content_type] and raw[content_type].get("body") is not None:
@norkans7 this was addressed but then reverted?

2024-05-13 19:24 UTC, rowanseymour requested changes

2024-05-13 19:35 UTC, rowanseymour approved these changes

2024-05-13 22:02 UTC, rowanseymour requested changes

2024-05-13 22:02 UTC, rowanseymour commented on temba/templates/types/twilio/type.py
> +            if raw[content_type].get("media", []):
this still feels wrong.. why is there a default value of `[]`? It's never going to be used because it's never going to be true.

2024-05-14 15:34 UTC, rowanseymour approved these changes

2024-05-14 15:34 UTC, merged