Python 3.11
nyaruka/rapidpro pull request #5320
Opened 2024-06-26 15:27 UTC by norkans7

2024-06-26 15:29 UTC, norkans7 commented on temba/channels/types/justcall/tests.py
> +            with self.assertRaisesRegex(ValidationError, "Unable to add webhook to JustCall: Failed try again later."):
Removed in 3.12

2024-06-26 15:29 UTC, norkans7 commented on temba/channels/types/justcall/tests.py
> -            with self.assertRaisesRegexp(ValidationError, "Unable to add webhook to JustCall: Failed try again later."):
Removed in 3.12

2024-06-28 07:18 UTC, matlads commented on pyproject.toml
> +python = "^3.11"
rapidpro seems to work just fine on python-3.10
```suggestion
python = ">=3.10<4"
```

2024-07-01 13:54 UTC, rowanseymour commented on pyproject.toml
> +python = "^3.11"
Currently yes but we'd like to start using newer Python features without worrying if they're supported on older versions so the goal is to get the required version to 3.12

2024-07-02 14:52 UTC, rowanseymour commented on .github/workflows/ci.yml
> +        python-version: ["3.11.x", "3.12.x"]
really don't want to do double tests - just make this PR be 3.11 so we can get it out there - and then worry about 3.12 separately

2024-07-02 14:59 UTC, rowanseymour commented on pyproject.toml
> +python = "^3.11"
@norkans7 in poetry `^3.11` means 3.11, 3.12, etc.. let's try `~3.11` to see if it installs with 3.11 even when 3.12 is available

2024-07-02 15:02 UTC, rowanseymour requested changes

2024-07-02 15:02 UTC, rowanseymour commented on pyproject.toml
> +python = "^3.11.9"
`~3.11`

2024-07-02 15:05 UTC, merged