Support FCM changes
nyaruka/rapidpro pull request #5411
Opened 2024-07-23 13:31 UTC by norkans7

needs https://github.com/nyaruka/courier/pull/762

2024-07-24 18:41 UTC, norkans7 commented on temba/channels/types/firebase/views.py
> +            label="Project ID",
replaced the FCM key with project ID for now, we need something unique to use ad address

2024-07-30 15:41 UTC, rowanseymour requested changes

2024-07-30 15:41 UTC, rowanseymour commented on temba/utils/fields.py
> +class PrettyJSONEncoder(json.JSONEncoder):  # pragma: needs cover
This can go in `temba.utils.json.PrettyEncoder` and does it need `# pragma: needs cover` ?

2024-07-30 16:00 UTC, rowanseymour requested changes

2024-07-30 16:00 UTC, rowanseymour commented on temba/utils/json.py
> +class PrettyJSONEncoder(json.JSONEncoder):
The other encoders/decoders in this file don't have `JSON` in the name because we typically import this module like `from temba.utils import json`

2024-07-30 16:27 UTC, rowanseymour requested changes

2024-07-30 16:27 UTC, rowanseymour commented on temba/channels/types/firebase/views.py
> +        )
This is weird.. asking them to enter the private key ID that is in the JSON below. Why not just extract it in `form_valid` ?

2024-07-31 14:36 UTC, rowanseymour approved these changes

2024-07-31 14:36 UTC, merged