Progress update
nyaruka/rapidpro pull request #5509
Opened 2024-09-25 18:58 UTC by ericnewcomer

2024-09-25 19:08 UTC, rowanseymour requested changes

2024-09-25 19:08 UTC, rowanseymour commented on temba/msgs/views.py
> +        permission = "msgs.broadcast_create"
`"msgs.broadcast_update"`

2024-09-25 19:08 UTC, rowanseymour commented on temba/msgs/views.py
> +            qs = super().derive_queryset(**kwargs)
this isn't filtering by org no?

2024-09-25 19:08 UTC, rowanseymour commented on temba/msgs/views.py
> +        permission = "msgs.broadcast_create"
`"msgs.broadcast_read"`

2024-09-25 19:08 UTC, rowanseymour commented on temba/settings_common.py
> +    "msgs.broadcast": ("scheduled", "scheduled_read", "scheduled_delete", "interrupt", "status"),
not needed

2024-09-25 19:08 UTC, rowanseymour commented on temba/flows/views.py
> +        permission = "flows.flow_start"
`"flows.flowstart_update"`

2024-09-25 19:08 UTC, rowanseymour commented on temba/flows/views.py
> +        permission = "flows.flow_start"
`"flows.flowstart_read"`

2024-09-26 02:08 UTC, ericnewcomer commented on temba/orgs/views.py
> -        if self.get_user().is_staff and org:
@rowanseymour so this touches permissions all over the place, but I'm not sure why org is required here. Any idea? This is to allow staff users to use the status endpoint, etc without an active org.

2024-09-26 02:08 UTC, ericnewcomer commented on templates/frame.html
> -                </temba-outbox-monitor>
no point in this thing anymore

2024-09-26 02:27 UTC, ericnewcomer commented on temba/flows/views.py
> +
Snuck this in. Background flows while not showing the in_a_flow checkbox could have it "enabled" by default.

2024-09-26 21:25 UTC, merged